"""Populate the Women's Fitness exercise library.

Safe to run multiple times — uses update_or_create keyed on exercise name.
Exercises that already exist in the general library (e.g. Plank, Glute Bridge)
are updated with recommended workout parameters but keep gender_category='all'
so they remain visible for all users.
"""
from django.core.management.base import BaseCommand
from workout.models import Exercise

# ──────────────────────────────────────────────────────────────────────────────
# Women's Fitness exercise data, organized by category
# ──────────────────────────────────────────────────────────────────────────────

WOMENS_EXERCISES = [
    # ── Lower Body & Glutes ──────────────────────────────────────────────────
    {
        'name': 'Bodyweight Squat',
        'category': 'Lower Body & Glutes',
        'body_part': 'Legs',
        'muscles_targeted': 'Quadriceps, Glutes, Hamstrings',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'A simple and effective lower-body exercise that strengthens your legs and glutes using only your body weight. Perfect for beginners.',
        'instructions': '1. Stand with feet shoulder-width apart, toes slightly out.\n2. Push your hips back and bend your knees as if sitting in a chair.\n3. Lower until your thighs are parallel to the floor (or as low as comfortable).\n4. Press through your heels to stand back up.\n5. Keep your chest up and core tight throughout.',
        'beginner_tips': 'If you feel unstable, try squatting to a chair first. Focus on keeping your knees in line with your toes.',
    },
    {
        'name': 'Goblet Squat',
        'category': 'Lower Body & Glutes',
        'body_part': 'Legs',
        'muscles_targeted': 'Quadriceps, Glutes, Core',
        'equipment_type': 'dumbbell',
        'is_bodyweight': False,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
        'description': 'Hold a dumbbell close to your chest while squatting. The weight in front helps you keep an upright posture and go deeper.',
        'instructions': '1. Hold a dumbbell vertically at chest height with both hands.\n2. Stand with feet slightly wider than shoulder-width.\n3. Squat down by pushing hips back and bending knees.\n4. Keep the dumbbell close to your chest the entire time.\n5. Push through your heels to return to standing.',
        'beginner_tips': 'Start with a light dumbbell (2–5 kg). The weight actually helps your balance.',
    },
    {
        'name': 'Sumo Squat',
        'category': 'Lower Body & Glutes',
        'body_part': 'Legs',
        'muscles_targeted': 'Inner Thighs, Glutes, Quadriceps',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'A wide-stance squat that targets your inner thighs and glutes more than a regular squat. Great for toning the lower body.',
        'instructions': '1. Stand with feet wider than shoulder-width, toes pointed outward at 45 degrees.\n2. Keep your back straight and core engaged.\n3. Lower your body by bending your knees outward.\n4. Go down until your thighs are parallel to the floor.\n5. Push through your heels to stand back up.',
        'beginner_tips': 'Keep your knees tracking over your toes. Start without any weight.',
    },
    {
        'name': 'Bulgarian Split Squat',
        'category': 'Lower Body & Glutes',
        'body_part': 'Legs',
        'muscles_targeted': 'Quadriceps, Glutes, Hamstrings, Balance',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'intermediate',
        'is_beginner_friendly': False,
        'recommended_sets': '3',
        'recommended_reps': '10 each leg',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
        'description': 'A single-leg squat with your back foot elevated on a bench or step. Excellent for building leg strength and balance.',
        'instructions': '1. Stand about 2 feet in front of a bench or sturdy chair.\n2. Place the top of one foot on the bench behind you.\n3. Lower your body by bending your front knee until your thigh is parallel to the floor.\n4. Push through your front heel to return to standing.\n5. Complete all reps on one side, then switch legs.',
        'beginner_tips': 'Hold onto a wall for balance at first. Use a lower surface like a step if a bench feels too high.',
    },
    {
        'name': 'Reverse Lunge',
        'category': 'Lower Body & Glutes',
        'body_part': 'Legs',
        'muscles_targeted': 'Glutes, Quadriceps, Hamstrings',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '10 each leg',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'Step backward into a lunge position. Easier on the knees than forward lunges and great for targeting the glutes.',
        'instructions': '1. Stand tall with feet hip-width apart.\n2. Step one foot back about 2–3 feet.\n3. Lower your body until both knees form 90-degree angles.\n4. Your back knee should almost touch the floor.\n5. Push through your front heel to return to the starting position.\n6. Alternate legs or complete all reps on one side.',
        'beginner_tips': 'Take a shorter step back if you feel off-balance. Hold onto a chair for support if needed.',
    },
    {
        'name': 'Walking Lunges',
        'category': 'Lower Body & Glutes',
        'body_part': 'Legs',
        'muscles_targeted': 'Quadriceps, Glutes, Hamstrings, Balance',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'intermediate',
        'is_beginner_friendly': False,
        'recommended_sets': '3',
        'recommended_reps': '10 each leg',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
        'description': 'Lunges performed while walking forward. A dynamic exercise that builds leg strength and coordination.',
        'instructions': '1. Stand tall with feet together.\n2. Step forward with one leg and lower your body into a lunge.\n3. Push through your front heel and bring your back foot forward.\n4. Step into the next lunge with the opposite leg.\n5. Continue alternating as you walk forward.',
        'beginner_tips': 'Start with shorter steps and a slow pace. You can hold light dumbbells for extra challenge once comfortable.',
    },
    {
        'name': 'Step-Ups',
        'category': 'Lower Body & Glutes',
        'body_part': 'Legs',
        'muscles_targeted': 'Glutes, Quadriceps, Hamstrings',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '10 each leg',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'Step up onto a raised surface like a bench, step, or sturdy chair. A simple and functional exercise for your legs and glutes.',
        'instructions': '1. Stand in front of a sturdy step or bench.\n2. Place your entire right foot on the step.\n3. Press through your right heel to lift your body up.\n4. Stand fully on the step, then slowly lower back down.\n5. Complete all reps on one leg, then switch.',
        'beginner_tips': 'Use a lower step to start. Make sure the surface is stable and won\'t move.',
    },
    {
        'name': 'Glute Bridge',
        'category': 'Lower Body & Glutes',
        'body_part': 'Legs',
        'muscles_targeted': 'Glutes, Hamstrings, Lower Back',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'Lie on your back and push your hips up to the ceiling. One of the best beginner-friendly exercises for activating and strengthening the glutes.',
        'instructions': '1. Lie on your back with knees bent and feet flat on the floor, hip-width apart.\n2. Place your arms at your sides, palms down.\n3. Push through your heels to lift your hips toward the ceiling.\n4. Squeeze your glutes at the top and hold for 1–2 seconds.\n5. Slowly lower your hips back to the floor.',
        'beginner_tips': 'Focus on squeezing your glutes at the top. Don\'t push up using your lower back.',
    },
    {
        'name': 'Single-Leg Glute Bridge',
        'category': 'Lower Body & Glutes',
        'body_part': 'Legs',
        'muscles_targeted': 'Glutes, Hamstrings, Core Stability',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'intermediate',
        'is_beginner_friendly': False,
        'recommended_sets': '3',
        'recommended_reps': '10 each leg',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'A single-leg variation of the glute bridge for extra glute activation and core stability.',
        'instructions': '1. Lie on your back with knees bent, feet flat on the floor.\n2. Extend one leg straight up toward the ceiling.\n3. Push through the heel of the grounded foot to lift your hips.\n4. Squeeze your glutes at the top.\n5. Slowly lower and repeat. Switch legs after completing all reps.',
        'beginner_tips': 'Master the regular glute bridge first. Keep your hips level — don\'t let them tilt to one side.',
    },
    {
        'name': 'Hip Thrust',
        'category': 'Lower Body & Glutes',
        'body_part': 'Legs',
        'muscles_targeted': 'Glutes, Hamstrings',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'intermediate',
        'is_beginner_friendly': False,
        'recommended_sets': '3–4',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
        'description': 'Your upper back rests on a bench while you drive your hips upward. One of the most effective exercises for building strong glutes.',
        'instructions': '1. Sit on the floor with your upper back against a bench.\n2. Place your feet flat on the floor, hip-width apart, knees bent.\n3. Drive through your heels to push your hips up until your body forms a straight line from shoulders to knees.\n4. Squeeze your glutes hard at the top.\n5. Slowly lower your hips back down.',
        'beginner_tips': 'Start with bodyweight only. You can place a dumbbell on your hips once you\'re comfortable with the movement.',
    },
    {
        'name': 'Romanian Deadlift',
        'category': 'Lower Body & Glutes',
        'body_part': 'Legs',
        'muscles_targeted': 'Hamstrings, Glutes, Lower Back',
        'equipment_type': 'dumbbell',
        'is_bodyweight': False,
        'difficulty': 'intermediate',
        'is_beginner_friendly': False,
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
        'description': 'A hip-hinge movement that stretches and strengthens your hamstrings and glutes. Use dumbbells for a more accessible version.',
        'instructions': '1. Hold a dumbbell in each hand in front of your thighs.\n2. Stand with feet hip-width apart, slight bend in your knees.\n3. Hinge forward at the hips, pushing your butt back.\n4. Lower the dumbbells along your legs until you feel a stretch in your hamstrings.\n5. Squeeze your glutes to stand back up.',
        'beginner_tips': 'Keep the weights close to your body. The movement comes from your hips, not your lower back. Start very light.',
    },
    {
        'name': 'Donkey Kicks',
        'category': 'Lower Body & Glutes',
        'body_part': 'Legs',
        'muscles_targeted': 'Glutes',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '15 each leg',
        'recommended_duration': '',
        'recommended_rest': '30 seconds',
        'description': 'On all fours, kick one leg up toward the ceiling. A simple glute isolation exercise you can do anywhere.',
        'instructions': '1. Start on all fours — hands under shoulders, knees under hips.\n2. Keep your right knee bent at 90 degrees.\n3. Lift your right leg up, pushing your foot toward the ceiling.\n4. Squeeze your glute at the top.\n5. Lower back down without touching the floor and repeat.\n6. Switch legs after completing all reps.',
        'beginner_tips': 'Keep your core engaged so your back doesn\'t arch. Move slowly and focus on the squeeze.',
    },
    {
        'name': 'Fire Hydrants',
        'category': 'Lower Body & Glutes',
        'body_part': 'Legs',
        'muscles_targeted': 'Glutes, Hip Abductors',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '15 each leg',
        'recommended_duration': '',
        'recommended_rest': '30 seconds',
        'description': 'On all fours, lift your knee out to the side. Targets the outer glute and hip muscles for better stability.',
        'instructions': '1. Start on all fours — hands under shoulders, knees under hips.\n2. Keeping your knee bent at 90 degrees, lift your right knee out to the side.\n3. Raise it until your thigh is parallel to the floor (or as high as comfortable).\n4. Slowly lower back down.\n5. Complete all reps, then switch sides.',
        'beginner_tips': 'Don\'t lift too high at first. Keep your hips square to the floor.',
    },
    {
        'name': 'Curtsy Lunge',
        'category': 'Lower Body & Glutes',
        'body_part': 'Legs',
        'muscles_targeted': 'Glutes, Inner Thighs, Quadriceps',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'intermediate',
        'is_beginner_friendly': False,
        'recommended_sets': '3',
        'recommended_reps': '10 each leg',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'Step one leg behind and across your body, like a curtsy. Targets the outer glutes and inner thighs.',
        'instructions': '1. Stand with feet hip-width apart.\n2. Step your right foot diagonally behind your left leg.\n3. Bend both knees to lower into a lunge.\n4. Push through your left heel to return to standing.\n5. Alternate legs or complete all reps on one side.',
        'beginner_tips': 'Start with a shallow lunge. Hold onto something for balance if needed.',
    },
    {
        'name': 'Standing Leg Raises',
        'category': 'Lower Body & Glutes',
        'body_part': 'Legs',
        'muscles_targeted': 'Hip Flexors, Glutes, Core',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '12 each leg',
        'recommended_duration': '',
        'recommended_rest': '30 seconds',
        'description': 'Stand on one leg and raise the other in different directions. Builds hip strength and balance without any equipment.',
        'instructions': '1. Stand tall, holding a wall or chair for balance if needed.\n2. Keeping your leg straight, slowly lift it forward.\n3. Hold briefly at the top, then lower slowly.\n4. You can also raise the leg to the side or behind you.\n5. Complete all reps, then switch legs.',
        'beginner_tips': 'Hold onto a wall for balance. You don\'t need to lift very high — focus on control.',
    },

    # ── Upper Body ────────────────────────────────────────────────────────────
    {
        'name': 'Wall Push-Ups',
        'category': 'Upper Body',
        'body_part': 'Chest',
        'muscles_targeted': 'Chest, Shoulders, Triceps',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'Push-ups against a wall — the easiest variation and perfect for absolute beginners building upper-body strength.',
        'instructions': '1. Stand facing a wall, about arm\'s length away.\n2. Place your palms flat on the wall at shoulder height and width.\n3. Bend your elbows to bring your chest toward the wall.\n4. Push back to the starting position.\n5. Keep your body in a straight line throughout.',
        'beginner_tips': 'The farther your feet are from the wall, the harder it gets. Start close and gradually move back.',
    },
    {
        'name': 'Incline Push-Ups',
        'category': 'Upper Body',
        'body_part': 'Chest',
        'muscles_targeted': 'Chest, Shoulders, Triceps',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'Push-ups with your hands on an elevated surface like a bench or counter. A great progression from wall push-ups.',
        'instructions': '1. Place your hands on a bench, counter, or sturdy elevated surface.\n2. Walk your feet back until your body forms a straight line.\n3. Bend your elbows to lower your chest toward the surface.\n4. Push back up to the starting position.\n5. Keep your core tight and body straight.',
        'beginner_tips': 'The higher the surface, the easier it is. Lower the surface as you get stronger.',
    },
    {
        'name': 'Knee Push-Ups',
        'category': 'Upper Body',
        'body_part': 'Chest',
        'muscles_targeted': 'Chest, Shoulders, Triceps',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '8–12',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'Push-ups performed from your knees instead of your toes. Builds upper-body strength for full push-ups.',
        'instructions': '1. Start in a push-up position but with your knees on the floor.\n2. Keep your body in a straight line from head to knees.\n3. Lower your chest toward the floor by bending your elbows.\n4. Push back up to the starting position.\n5. Don\'t let your hips sag or pike up.',
        'beginner_tips': 'Place a towel or mat under your knees for comfort. Cross your ankles behind you.',
    },
    {
        'name': 'Standard Push-Ups',
        'category': 'Upper Body',
        'body_part': 'Chest',
        'muscles_targeted': 'Chest, Shoulders, Triceps, Core',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'intermediate',
        'is_beginner_friendly': False,
        'recommended_sets': '3',
        'recommended_reps': '8–15',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
        'description': 'The classic push-up. A full-body exercise that primarily targets the chest, shoulders, and triceps.',
        'instructions': '1. Start in a high plank position with hands slightly wider than shoulder-width.\n2. Keep your body in a straight line from head to heels.\n3. Lower your chest to the floor by bending your elbows.\n4. Push back up to the starting position.\n5. Keep your core tight throughout.',
        'beginner_tips': 'If full push-ups are too hard, start with knee push-ups and progress from there.',
    },
    {
        'name': 'Dumbbell Shoulder Press',
        'category': 'Upper Body',
        'body_part': 'Shoulders',
        'muscles_targeted': 'Shoulders, Triceps',
        'equipment_type': 'dumbbell',
        'is_bodyweight': False,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
        'description': 'Press dumbbells overhead from shoulder height. A fundamental upper-body exercise for building shoulder strength.',
        'instructions': '1. Hold a dumbbell in each hand at shoulder height, palms facing forward.\n2. Press the dumbbells straight up overhead until your arms are fully extended.\n3. Slowly lower the dumbbells back to shoulder height.\n4. Keep your core engaged and avoid arching your back.',
        'beginner_tips': 'Start with very light weights (1–3 kg). You can do this seated for more stability.',
    },
    {
        'name': 'Dumbbell Lateral Raise',
        'category': 'Upper Body',
        'body_part': 'Shoulders',
        'muscles_targeted': 'Side Shoulders (Deltoids)',
        'equipment_type': 'dumbbell',
        'is_bodyweight': False,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'Raise dumbbells out to the sides to shoulder height. Shapes and strengthens the side shoulders.',
        'instructions': '1. Stand with feet hip-width apart, a light dumbbell in each hand.\n2. Keep your arms slightly bent at the elbows.\n3. Raise both arms out to the sides until they reach shoulder height.\n4. Pause briefly, then slowly lower back down.\n5. Don\'t swing the weights — use slow, controlled movements.',
        'beginner_tips': 'Use very light weights (1–2 kg). Lead with your elbows, not your hands.',
    },
    {
        'name': 'Dumbbell Front Raise',
        'category': 'Upper Body',
        'body_part': 'Shoulders',
        'muscles_targeted': 'Front Shoulders (Anterior Deltoids)',
        'equipment_type': 'dumbbell',
        'is_bodyweight': False,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'Raise dumbbells in front of you to shoulder height. Targets the front of the shoulders.',
        'instructions': '1. Stand with feet hip-width apart, a dumbbell in each hand, palms facing your thighs.\n2. With a slight bend in your elbows, raise one or both dumbbells straight in front of you.\n3. Lift to shoulder height.\n4. Slowly lower back down.\n5. Keep your core tight and avoid leaning back.',
        'beginner_tips': 'Start light and alternate arms if lifting both feels too difficult.',
    },
    {
        'name': 'Dumbbell Bicep Curl',
        'category': 'Upper Body',
        'body_part': 'Arms',
        'muscles_targeted': 'Biceps',
        'equipment_type': 'dumbbell',
        'is_bodyweight': False,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'Curl dumbbells up toward your shoulders. The most popular exercise for building arm strength.',
        'instructions': '1. Stand with feet hip-width apart, a dumbbell in each hand, arms at your sides.\n2. Keep your elbows close to your body.\n3. Curl the dumbbells up toward your shoulders by bending your elbows.\n4. Squeeze your biceps at the top.\n5. Slowly lower back down.',
        'beginner_tips': 'Don\'t swing your body. Keep your upper arms still — only your forearms should move.',
    },
    {
        'name': 'Hammer Curl',
        'category': 'Upper Body',
        'body_part': 'Arms',
        'muscles_targeted': 'Biceps, Forearms',
        'equipment_type': 'dumbbell',
        'is_bodyweight': False,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'A bicep curl with palms facing each other. Works the biceps and forearms together.',
        'instructions': '1. Stand with a dumbbell in each hand, palms facing your body (neutral grip).\n2. Keep your elbows close to your sides.\n3. Curl the dumbbells up toward your shoulders.\n4. Slowly lower back down.\n5. Keep your wrists straight throughout.',
        'beginner_tips': 'Start with a weight you can control for all reps. This is easier on the wrists than regular curls.',
    },
    {
        'name': 'Tricep Kickback',
        'category': 'Upper Body',
        'body_part': 'Arms',
        'muscles_targeted': 'Triceps',
        'equipment_type': 'dumbbell',
        'is_bodyweight': False,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '10–12 each arm',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'Bend forward and extend your arm behind you. A simple and effective exercise for toning the back of your arms.',
        'instructions': '1. Hold a dumbbell in one hand.\n2. Bend forward at the hips with a flat back.\n3. Bring your upper arm parallel to your body, elbow bent at 90 degrees.\n4. Extend your forearm backward until your arm is straight.\n5. Squeeze your tricep, then slowly bend your elbow back.\n6. Complete all reps, then switch arms.',
        'beginner_tips': 'Use a light weight. Keep your upper arm still — only your forearm should move.',
    },
    {
        'name': 'Overhead Tricep Extension',
        'category': 'Upper Body',
        'body_part': 'Arms',
        'muscles_targeted': 'Triceps',
        'equipment_type': 'dumbbell',
        'is_bodyweight': False,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'Hold a dumbbell overhead with both hands and lower it behind your head. Targets the triceps for toned arms.',
        'instructions': '1. Hold one dumbbell with both hands overhead, arms extended.\n2. Keep your upper arms close to your ears.\n3. Slowly lower the dumbbell behind your head by bending your elbows.\n4. Extend your arms back up to the starting position.\n5. Keep your core tight and avoid arching your back.',
        'beginner_tips': 'Start with a light weight. You can do this seated for more stability.',
    },
    {
        'name': 'Dumbbell Row',
        'category': 'Upper Body',
        'body_part': 'Back',
        'muscles_targeted': 'Back, Biceps, Rear Shoulders',
        'equipment_type': 'dumbbell',
        'is_bodyweight': False,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '10–12 each arm',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
        'description': 'Pull a dumbbell toward your hip while bent over. Strengthens your back and improves posture.',
        'instructions': '1. Place one hand and knee on a bench for support.\n2. Hold a dumbbell in the other hand, arm hanging straight down.\n3. Pull the dumbbell up toward your hip, squeezing your shoulder blade.\n4. Slowly lower the dumbbell back down.\n5. Complete all reps, then switch sides.',
        'beginner_tips': 'Keep your back flat and core tight. Think about pulling with your elbow, not your hand.',
    },
    {
        'name': 'Resistance-Band Row',
        'category': 'Upper Body',
        'body_part': 'Back',
        'muscles_targeted': 'Back, Biceps, Rear Shoulders',
        'equipment_type': 'resistance_band',
        'is_bodyweight': False,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'Sit on the floor with a resistance band around your feet and row the band toward you. A gentle way to strengthen your back.',
        'instructions': '1. Sit on the floor with legs extended.\n2. Loop a resistance band around your feet and hold the ends.\n3. Sit tall with a straight back.\n4. Pull the band toward your waist, squeezing your shoulder blades together.\n5. Slowly release back to the starting position.',
        'beginner_tips': 'Use a lighter band to start. Focus on squeezing your shoulder blades at the end of each pull.',
    },

    # ── Core ──────────────────────────────────────────────────────────────────
    {
        'name': 'Plank',
        'category': 'Core',
        'body_part': 'Core',
        'muscles_targeted': 'Core, Shoulders, Back',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '',
        'recommended_duration': '20–30 seconds',
        'recommended_rest': '45 seconds',
        'description': 'Hold your body in a straight line supported on your forearms and toes. One of the best exercises for core strength.',
        'instructions': '1. Place your forearms on the floor with elbows under your shoulders.\n2. Extend your legs behind you, resting on your toes.\n3. Keep your body in a straight line from head to heels.\n4. Engage your core and hold the position.\n5. Don\'t let your hips sag or pike up.',
        'beginner_tips': 'Start with shorter holds (10–15 seconds) and build up. If it\'s too hard, try the knee plank first.',
    },
    {
        'name': 'Knee Plank',
        'category': 'Core',
        'body_part': 'Core',
        'muscles_targeted': 'Core, Shoulders',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '',
        'recommended_duration': '20–30 seconds',
        'recommended_rest': '45 seconds',
        'description': 'A beginner-friendly plank variation done from your knees. Builds core strength with less demand on the upper body.',
        'instructions': '1. Place your forearms on the floor with elbows under your shoulders.\n2. Rest on your knees instead of your toes.\n3. Keep a straight line from your head to your knees.\n4. Engage your core and hold.\n5. Don\'t let your hips sag.',
        'beginner_tips': 'This is a great starting point. Once you can hold for 30 seconds comfortably, try the full plank.',
    },
    {
        'name': 'Side Plank',
        'category': 'Core',
        'body_part': 'Core',
        'muscles_targeted': 'Obliques, Core, Shoulders',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'intermediate',
        'is_beginner_friendly': False,
        'recommended_sets': '3',
        'recommended_reps': '',
        'recommended_duration': '15–30 seconds each side',
        'recommended_rest': '45 seconds',
        'description': 'Hold your body sideways on one forearm. Targets the side muscles of your core (obliques).',
        'instructions': '1. Lie on your side with your forearm on the floor, elbow under your shoulder.\n2. Stack your feet or stagger them for more balance.\n3. Lift your hips to create a straight line from head to feet.\n4. Hold the position.\n5. Repeat on the other side.',
        'beginner_tips': 'Start by bending your bottom knee for support. Build up to the full version gradually.',
    },
    {
        'name': 'Dead Bug',
        'category': 'Core',
        'body_part': 'Core',
        'muscles_targeted': 'Deep Core, Hip Flexors',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '8–10 each side',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'Lie on your back and move opposite arms and legs. A safe, effective exercise for deep core strength without straining your back.',
        'instructions': '1. Lie on your back with arms extended toward the ceiling.\n2. Lift your legs so your knees are bent at 90 degrees above your hips.\n3. Slowly lower your right arm behind your head while extending your left leg.\n4. Return to the starting position.\n5. Repeat on the opposite side.',
        'beginner_tips': 'Press your lower back into the floor throughout the movement. Move slowly and with control.',
    },
    {
        'name': 'Bird Dog',
        'category': 'Core',
        'body_part': 'Core',
        'muscles_targeted': 'Core, Lower Back, Glutes',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '8–10 each side',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'On all fours, extend opposite arm and leg. Builds core stability and back strength safely.',
        'instructions': '1. Start on all fours — hands under shoulders, knees under hips.\n2. Extend your right arm forward and left leg backward simultaneously.\n3. Keep your back flat and hips level.\n4. Hold for 1–2 seconds.\n5. Return to starting position and switch sides.',
        'beginner_tips': 'Move slowly and focus on balance. If it\'s too hard, try extending just the arm or just the leg first.',
    },
    {
        'name': 'Bicycle Crunches',
        'category': 'Core',
        'body_part': 'Core',
        'muscles_targeted': 'Obliques, Rectus Abdominis',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'intermediate',
        'is_beginner_friendly': False,
        'recommended_sets': '3',
        'recommended_reps': '12–15 each side',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'A twisting crunch that targets both the front and side muscles of your core.',
        'instructions': '1. Lie on your back with hands behind your head.\n2. Lift your shoulders off the floor.\n3. Bring your right elbow toward your left knee while extending your right leg.\n4. Switch sides in a pedaling motion.\n5. Keep the movement slow and controlled — don\'t pull on your neck.',
        'beginner_tips': 'Focus on the rotation, not speed. Keep your lower back pressed into the floor.',
    },
    {
        'name': 'Reverse Crunches',
        'category': 'Core',
        'body_part': 'Core',
        'muscles_targeted': 'Lower Abdominals',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'intermediate',
        'is_beginner_friendly': False,
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'Instead of lifting your shoulders, you curl your hips up. Targets the lower part of your abs.',
        'instructions': '1. Lie on your back with arms at your sides.\n2. Lift your legs so knees are bent at 90 degrees.\n3. Contract your abs to curl your hips off the floor toward your chest.\n4. Slowly lower back to the starting position.\n5. Don\'t use momentum — use your core muscles.',
        'beginner_tips': 'This is a small movement. Focus on using your abs, not swinging your legs.',
    },
    {
        'name': 'Leg Raises',
        'category': 'Core',
        'body_part': 'Core',
        'muscles_targeted': 'Lower Abdominals, Hip Flexors',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'intermediate',
        'is_beginner_friendly': False,
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'Lie on your back and raise your legs straight up. A challenging core exercise for the lower abdominals.',
        'instructions': '1. Lie on your back with legs straight and arms at your sides.\n2. Press your lower back into the floor.\n3. Slowly raise your legs up until they point toward the ceiling.\n4. Slowly lower them back down without touching the floor.\n5. Keep your legs as straight as possible.',
        'beginner_tips': 'Bend your knees slightly if straight-leg raises are too difficult. Place your hands under your hips for lower back support.',
    },
    {
        'name': 'Mountain Climbers',
        'category': 'Core',
        'body_part': 'Core',
        'muscles_targeted': 'Core, Shoulders, Hip Flexors, Cardio',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'intermediate',
        'is_beginner_friendly': False,
        'recommended_sets': '3',
        'recommended_reps': '',
        'recommended_duration': '20–30 seconds',
        'recommended_rest': '45 seconds',
        'description': 'From a plank position, drive your knees toward your chest alternately. Combines core work with cardio.',
        'instructions': '1. Start in a high plank position with hands under shoulders.\n2. Drive your right knee toward your chest.\n3. Quickly switch, driving your left knee forward.\n4. Continue alternating at a pace you can control.\n5. Keep your hips level and core engaged.',
        'beginner_tips': 'Start slowly — speed it up as you get more comfortable. Focus on form before pace.',
    },
    {
        'name': 'Heel Taps',
        'category': 'Core',
        'body_part': 'Core',
        'muscles_targeted': 'Obliques',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '15 each side',
        'recommended_duration': '',
        'recommended_rest': '30 seconds',
        'description': 'Lie on your back with knees bent and reach side to side to tap your heels. A gentle, effective exercise for the obliques.',
        'instructions': '1. Lie on your back with knees bent, feet flat on the floor.\n2. Lift your shoulders slightly off the floor.\n3. Reach your right hand down to touch your right heel.\n4. Return to center, then reach your left hand to your left heel.\n5. Continue alternating sides.',
        'beginner_tips': 'Keep your lower back pressed to the floor. Move your whole upper body, not just your arm.',
    },

    # ── Cardio & Fat Burning ──────────────────────────────────────────────────
    {
        'name': 'Brisk Walking',
        'category': 'Cardio & Fat Burning',
        'body_part': 'Cardio',
        'muscles_targeted': 'Full Body, Cardiovascular System',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '1',
        'recommended_reps': '',
        'recommended_duration': '20–30 minutes',
        'recommended_rest': 'As needed',
        'description': 'Walk at a pace that gets your heart rate up. The simplest and most accessible form of cardio for all fitness levels.',
        'instructions': '1. Put on comfortable shoes.\n2. Walk at a pace where you can talk but are slightly breathless.\n3. Swing your arms naturally.\n4. Keep your head up and shoulders back.\n5. Aim for at least 20 minutes.',
        'beginner_tips': 'Start with 10–15 minutes and gradually increase. Walking outdoors or on a treadmill both work.',
    },
    {
        'name': 'Jogging',
        'category': 'Cardio & Fat Burning',
        'body_part': 'Cardio',
        'muscles_targeted': 'Legs, Cardiovascular System',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'intermediate',
        'is_beginner_friendly': False,
        'recommended_sets': '1',
        'recommended_reps': '',
        'recommended_duration': '15–30 minutes',
        'recommended_rest': 'Walk breaks as needed',
        'description': 'A gentle running pace that builds cardiovascular fitness and endurance. A step up from brisk walking.',
        'instructions': '1. Start with a 5-minute brisk walk to warm up.\n2. Begin jogging at a comfortable pace.\n3. You should be able to maintain a conversation.\n4. If you get too breathless, slow down to a walk.\n5. Cool down with a 5-minute walk.',
        'beginner_tips': 'Try the run/walk method: jog for 1 minute, walk for 2 minutes. Gradually increase jogging time.',
    },
    {
        'name': 'Running',
        'category': 'Cardio & Fat Burning',
        'body_part': 'Cardio',
        'muscles_targeted': 'Legs, Core, Cardiovascular System',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'advanced',
        'is_beginner_friendly': False,
        'recommended_sets': '1',
        'recommended_reps': '',
        'recommended_duration': '20–45 minutes',
        'recommended_rest': 'Walk breaks as needed',
        'description': 'Running at a moderate to fast pace for cardiovascular fitness and calorie burning.',
        'instructions': '1. Warm up with a 5-minute brisk walk or slow jog.\n2. Run at your chosen pace.\n3. Maintain good posture — head up, arms relaxed.\n4. Land midfoot, not on your heels.\n5. Cool down with a slow walk and stretch.',
        'beginner_tips': 'Build up to running gradually. Invest in proper running shoes for comfort and injury prevention.',
    },
    {
        'name': 'Cycling',
        'category': 'Cardio & Fat Burning',
        'body_part': 'Cardio',
        'muscles_targeted': 'Legs, Cardiovascular System',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '1',
        'recommended_reps': '',
        'recommended_duration': '20–40 minutes',
        'recommended_rest': 'As needed',
        'description': 'Riding a bicycle outdoors or on a stationary bike. A low-impact cardio option that\'s easy on the joints.',
        'instructions': '1. Adjust the seat so your leg is almost straight at the bottom of the pedal.\n2. Start pedaling at a comfortable pace.\n3. Gradually increase your speed or resistance.\n4. Keep your back straight and core engaged.\n5. Cool down by reducing speed for the last 5 minutes.',
        'beginner_tips': 'Start with a low resistance and comfortable pace. Cycling is great if you have joint issues.',
    },
    {
        'name': 'Jumping Jacks',
        'category': 'Cardio & Fat Burning',
        'body_part': 'Cardio',
        'muscles_targeted': 'Full Body, Cardiovascular System',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '',
        'recommended_duration': '30 seconds',
        'recommended_rest': '30 seconds',
        'description': 'Jump while spreading your arms and legs wide, then return. A classic warm-up and cardio exercise.',
        'instructions': '1. Stand with feet together, arms at your sides.\n2. Jump up, spreading your feet wide and raising your arms overhead.\n3. Jump again to return to the starting position.\n4. Continue at a steady rhythm.\n5. Land softly on the balls of your feet.',
        'beginner_tips': 'If jumping is too much, step one foot out at a time instead of jumping (step jacks).',
    },
    {
        'name': 'High Knees',
        'category': 'Cardio & Fat Burning',
        'body_part': 'Cardio',
        'muscles_targeted': 'Core, Hip Flexors, Legs, Cardio',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'intermediate',
        'is_beginner_friendly': False,
        'recommended_sets': '3',
        'recommended_reps': '',
        'recommended_duration': '20–30 seconds',
        'recommended_rest': '30 seconds',
        'description': 'Run in place while driving your knees up toward your chest. A high-intensity cardio exercise.',
        'instructions': '1. Stand tall with feet hip-width apart.\n2. Drive your right knee up toward your chest.\n3. Quickly switch, driving your left knee up.\n4. Pump your arms as if running.\n5. Keep your core tight and land softly.',
        'beginner_tips': 'Start at a slow marching pace and speed up as you feel comfortable.',
    },
    {
        'name': 'Butt Kicks',
        'category': 'Cardio & Fat Burning',
        'body_part': 'Cardio',
        'muscles_targeted': 'Hamstrings, Cardiovascular System',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '',
        'recommended_duration': '20–30 seconds',
        'recommended_rest': '30 seconds',
        'description': 'Run in place while kicking your heels up toward your glutes. A fun cardio exercise that also warms up your hamstrings.',
        'instructions': '1. Stand with feet hip-width apart.\n2. Jog in place, flicking your heels up toward your glutes.\n3. Try to touch your glutes with your heels.\n4. Keep your arms pumping naturally.\n5. Stay on the balls of your feet.',
        'beginner_tips': 'Start slowly. Focus on the heel flick rather than speed.',
    },
    {
        'name': 'Step Jacks',
        'category': 'Cardio & Fat Burning',
        'body_part': 'Cardio',
        'muscles_targeted': 'Full Body, Cardiovascular System',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '',
        'recommended_duration': '30 seconds',
        'recommended_rest': '30 seconds',
        'description': 'A low-impact version of jumping jacks. Step one foot out at a time instead of jumping — great for beginners or bad knees.',
        'instructions': '1. Stand with feet together, arms at your sides.\n2. Step your right foot out to the side while raising your arms overhead.\n3. Step your left foot out to join it.\n4. Step your right foot back to center, lowering your arms.\n5. Step your left foot in. Repeat.',
        'beginner_tips': 'This is perfect if jumping feels too intense. You can speed up the steps for more cardio.',
    },
    {
        'name': 'Skipping Rope',
        'category': 'Cardio & Fat Burning',
        'body_part': 'Cardio',
        'muscles_targeted': 'Calves, Shoulders, Core, Cardiovascular System',
        'equipment_type': 'jump_rope',
        'is_bodyweight': False,
        'difficulty': 'intermediate',
        'is_beginner_friendly': False,
        'recommended_sets': '3',
        'recommended_reps': '',
        'recommended_duration': '1–2 minutes',
        'recommended_rest': '30–60 seconds',
        'description': 'Jump over a skipping rope repeatedly. An excellent full-body cardio exercise that burns calories quickly.',
        'instructions': '1. Hold the rope handles at hip height.\n2. Swing the rope over your head.\n3. Jump just high enough to clear the rope.\n4. Land softly on the balls of your feet.\n5. Keep your elbows close to your body and use wrist movement.',
        'beginner_tips': 'Start without the rope — practice the jump timing. Then try with the rope at a slow pace.',
    },
    {
        'name': 'Dancing / Cardio Dance',
        'category': 'Cardio & Fat Burning',
        'body_part': 'Cardio',
        'muscles_targeted': 'Full Body, Cardiovascular System',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '1',
        'recommended_reps': '',
        'recommended_duration': '15–30 minutes',
        'recommended_rest': 'As needed',
        'description': 'Move your body to music! One of the most fun ways to get your heart rate up and burn calories.',
        'instructions': '1. Put on your favorite upbeat music.\n2. Start moving — there are no wrong moves!\n3. Add arm movements, steps, and hip movements.\n4. Keep moving for the duration of the song or playlist.\n5. Take breaks when you need them.',
        'beginner_tips': 'Follow along with a dance workout video online. No dance experience needed — just have fun!',
    },

    # ── Mobility & Recovery ───────────────────────────────────────────────────
    {
        'name': 'Cat-Cow Stretch',
        'category': 'Mobility & Recovery',
        'body_part': 'Full Body',
        'muscles_targeted': 'Spine, Core, Back',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '2–3',
        'recommended_reps': '8–10',
        'recommended_duration': '',
        'recommended_rest': '30 seconds',
        'description': 'Gently arch and round your back while on all fours. A soothing stretch that warms up and mobilizes the spine.',
        'instructions': '1. Start on all fours — hands under shoulders, knees under hips.\n2. Inhale: Drop your belly, lift your head and tailbone (Cow).\n3. Exhale: Round your back, tuck your chin and tailbone (Cat).\n4. Flow between the two positions slowly.\n5. Breathe deeply with each movement.',
        'beginner_tips': 'Move slowly and gently. Let your breath guide the movement.',
    },
    {
        'name': "Child's Pose",
        'category': 'Mobility & Recovery',
        'body_part': 'Full Body',
        'muscles_targeted': 'Back, Hips, Shoulders',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '2–3',
        'recommended_reps': '',
        'recommended_duration': '30–60 seconds',
        'recommended_rest': '20 seconds',
        'description': 'A restful yoga pose where you sit back on your heels with arms extended. Perfect for rest between exercises or cool-down.',
        'instructions': '1. Kneel on the floor with toes together and knees hip-width apart.\n2. Sit your hips back toward your heels.\n3. Walk your hands forward and lower your forehead to the floor.\n4. Relax your arms and shoulders.\n5. Breathe deeply and hold.',
        'beginner_tips': 'If your hips don\'t reach your heels, place a cushion between them. Widen your knees if it\'s uncomfortable.',
    },
    {
        'name': 'Cobra Stretch',
        'category': 'Mobility & Recovery',
        'body_part': 'Core',
        'muscles_targeted': 'Abdominals, Chest, Spine',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '2–3',
        'recommended_reps': '',
        'recommended_duration': '15–30 seconds',
        'recommended_rest': '20 seconds',
        'description': 'Lie face down and gently push your upper body up. Opens the chest and stretches the front of the body.',
        'instructions': '1. Lie face down with hands under your shoulders.\n2. Press your hips into the floor.\n3. Slowly push your chest up, straightening your arms partially.\n4. Keep your shoulders down and away from your ears.\n5. Hold the stretch and breathe deeply.',
        'beginner_tips': 'Don\'t straighten your arms fully. Lift only as high as comfortable — your hips should stay on the floor.',
    },
    {
        'name': 'Hip Flexor Stretch',
        'category': 'Mobility & Recovery',
        'body_part': 'Legs',
        'muscles_targeted': 'Hip Flexors, Quadriceps',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '2',
        'recommended_reps': '',
        'recommended_duration': '30 seconds each side',
        'recommended_rest': '15 seconds',
        'description': 'A kneeling stretch for tight hip flexors — especially helpful if you sit a lot during the day.',
        'instructions': '1. Kneel on your right knee with your left foot flat on the floor in front.\n2. Keep your back straight and core engaged.\n3. Gently push your hips forward until you feel a stretch in the front of your right hip.\n4. Hold the stretch.\n5. Switch sides.',
        'beginner_tips': 'Place a towel under your knee for comfort. Don\'t lean forward — keep your torso upright.',
    },
    {
        'name': 'Hamstring Stretch',
        'category': 'Mobility & Recovery',
        'body_part': 'Legs',
        'muscles_targeted': 'Hamstrings',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '2',
        'recommended_reps': '',
        'recommended_duration': '30 seconds each side',
        'recommended_rest': '15 seconds',
        'description': 'Stretch the back of your thigh while sitting or standing. Helps with flexibility and reduces leg stiffness.',
        'instructions': '1. Sit on the floor with one leg extended and the other bent.\n2. Reach toward your toes on the extended leg.\n3. Keep your back straight — don\'t round your spine.\n4. Hold when you feel a gentle stretch.\n5. Switch legs.',
        'beginner_tips': 'You don\'t need to touch your toes. Reach as far as comfortable and hold.',
    },
    {
        'name': 'Butterfly Stretch',
        'category': 'Mobility & Recovery',
        'body_part': 'Legs',
        'muscles_targeted': 'Inner Thighs, Hips',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '2',
        'recommended_reps': '',
        'recommended_duration': '30–60 seconds',
        'recommended_rest': '15 seconds',
        'description': 'Sit with the soles of your feet together and gently press your knees toward the floor. Opens up the hips and inner thighs.',
        'instructions': '1. Sit on the floor with your back straight.\n2. Bring the soles of your feet together, knees out to the sides.\n3. Hold your feet with your hands.\n4. Gently press your knees toward the floor using your elbows.\n5. Hold and breathe deeply.',
        'beginner_tips': 'Don\'t force your knees down. Sit on a cushion if your hips feel tight.',
    },
    {
        'name': 'Glute Stretch',
        'category': 'Mobility & Recovery',
        'body_part': 'Legs',
        'muscles_targeted': 'Glutes, Hips',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '2',
        'recommended_reps': '',
        'recommended_duration': '30 seconds each side',
        'recommended_rest': '15 seconds',
        'description': 'Cross one ankle over the opposite knee and lean forward. A seated stretch that targets the glute muscles.',
        'instructions': '1. Sit on a chair or lie on your back.\n2. Cross your right ankle over your left knee.\n3. Gently pull your left thigh toward your chest (or lean forward if sitting).\n4. You should feel a stretch in your right glute.\n5. Hold and switch sides.',
        'beginner_tips': 'This stretch should feel good, not painful. Adjust the intensity by how far you lean.',
    },
    {
        'name': 'Shoulder Stretch',
        'category': 'Mobility & Recovery',
        'body_part': 'Shoulders',
        'muscles_targeted': 'Shoulders, Upper Back',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '2',
        'recommended_reps': '',
        'recommended_duration': '20–30 seconds each side',
        'recommended_rest': '15 seconds',
        'description': 'Pull one arm across your chest to stretch the shoulder. Simple and effective for shoulder flexibility.',
        'instructions': '1. Stand or sit tall.\n2. Extend your right arm across your chest.\n3. Use your left hand to gently pull the right arm closer to your body.\n4. You should feel a stretch in your right shoulder.\n5. Hold, then switch arms.',
        'beginner_tips': 'Don\'t pull too hard. The stretch should be gentle and comfortable.',
    },
    {
        'name': 'Chest Stretch',
        'category': 'Mobility & Recovery',
        'body_part': 'Chest',
        'muscles_targeted': 'Chest, Front Shoulders',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '2',
        'recommended_reps': '',
        'recommended_duration': '20–30 seconds',
        'recommended_rest': '15 seconds',
        'description': 'Open up your chest by clasping your hands behind your back. Helps counteract poor posture from sitting.',
        'instructions': '1. Stand tall with feet hip-width apart.\n2. Clasp your hands behind your back.\n3. Straighten your arms and gently lift them.\n4. Squeeze your shoulder blades together.\n5. Hold and breathe deeply.',
        'beginner_tips': 'If you can\'t clasp your hands, hold a towel between them. Focus on opening the chest.',
    },
    {
        'name': 'Full-Body Stretch',
        'category': 'Mobility & Recovery',
        'body_part': 'Full Body',
        'muscles_targeted': 'Full Body',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '1',
        'recommended_reps': '',
        'recommended_duration': '5–10 minutes',
        'recommended_rest': '',
        'description': 'A complete stretching routine that touches every major muscle group. Perfect for cool-downs or rest days.',
        'instructions': '1. Start with neck circles — slowly rotate your head in each direction.\n2. Roll your shoulders forward and backward.\n3. Stretch each arm across your chest.\n4. Do a standing forward fold, reaching toward your toes.\n5. Stretch each quadricep by pulling your heel to your glute.\n6. Finish with a seated butterfly stretch and deep breathing.',
        'beginner_tips': 'Move slowly and gently. Never bounce in a stretch. Hold each position for 15–30 seconds.',
    },

    # ── Beginner-Friendly (some are shared with other categories) ─────────────
    {
        'name': 'Chair Squat',
        'category': 'Beginner-Friendly',
        'body_part': 'Legs',
        'muscles_targeted': 'Quadriceps, Glutes',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'Squat down to a chair and stand back up. The chair gives you confidence and something to aim for.',
        'instructions': '1. Stand in front of a sturdy chair with feet shoulder-width apart.\n2. Slowly lower your body as if sitting down.\n3. Lightly touch the chair seat with your glutes.\n4. Push through your heels to stand back up.\n5. Keep your chest up throughout.',
        'beginner_tips': 'Start by actually sitting down and standing up. As you get stronger, just tap the chair.',
    },
    {
        'name': 'Marching in Place',
        'category': 'Beginner-Friendly',
        'body_part': 'Cardio',
        'muscles_targeted': 'Legs, Core, Cardiovascular System',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '',
        'recommended_duration': '1–2 minutes',
        'recommended_rest': '30 seconds',
        'description': 'Simply march in place, lifting your knees high. The most accessible warm-up and light cardio exercise.',
        'instructions': '1. Stand tall with feet together.\n2. Lift your right knee up toward your waist.\n3. Lower it and lift your left knee.\n4. Swing your arms naturally as you march.\n5. Keep a steady rhythm.',
        'beginner_tips': 'Lift your knees as high as comfortable. Hold onto a wall if you need balance support.',
    },
    {
        'name': 'Bodyweight Lunge',
        'category': 'Beginner-Friendly',
        'body_part': 'Legs',
        'muscles_targeted': 'Quadriceps, Glutes, Hamstrings',
        'equipment_type': 'bodyweight',
        'is_bodyweight': True,
        'difficulty': 'beginner',
        'is_beginner_friendly': True,
        'recommended_sets': '3',
        'recommended_reps': '8–10 each leg',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
        'description': 'A basic forward lunge using just your body weight. Builds leg strength and balance.',
        'instructions': '1. Stand tall with feet together.\n2. Step forward with one leg.\n3. Lower your body until both knees form 90-degree angles.\n4. Push through your front heel to return to standing.\n5. Alternate legs.',
        'beginner_tips': 'Take a shorter step if you feel wobbly. Hold onto a wall or chair for balance.',
    },
]

# Exercises that already exist in the general library.
# These should be updated with women's recommended parameters but
# keep gender_category='all' so they remain visible for all users.
SHARED_EXERCISE_NAMES = {
    'Glute Bridge', 'Plank', 'Side Plank', 'Dead Bug', 'Bird Dog',
    'Mountain Climbers', 'Jumping Jacks', 'High Knees', 'Running',
    'Cycling', 'Walking Lunges', 'Bulgarian Split Squat', 'Hip Thrust',
    'Romanian Deadlift', 'Dumbbell Shoulder Press', 'Hammer Curl',
    'Overhead Tricep Extension', 'Dumbbell Row', 'Goblet Squat',
    'Knee Push-Up', 'Incline Push-Up',
    'Wall Push-Up',
    'Step-Up',
    'Standing Calf Raise',
}

# Women's fitness category display order
WOMENS_CATEGORIES = [
    'Beginner-Friendly',
    'Lower Body & Glutes',
    'Upper Body',
    'Core',
    'Cardio & Fat Burning',
    'Mobility & Recovery',
]


class Command(BaseCommand):
    help = 'Populate the Women\'s Fitness exercise library (safe to run multiple times).'

    def handle(self, *args, **options):
        from workout.exercise_cleanup import normalize_name

        created_count = 0
        updated_count = 0

        for data in WOMENS_EXERCISES:
            name = normalize_name(data['name'])
            is_shared = name in SHARED_EXERCISE_NAMES or any(
                normalize_name(s) == name for s in SHARED_EXERCISE_NAMES
            )

            defaults = {
                'category': data['category'],
                'body_part': data['body_part'],
                'muscles_targeted': data['muscles_targeted'],
                'equipment_type': data['equipment_type'],
                'is_bodyweight': data['is_bodyweight'],
                'difficulty': data['difficulty'],
                'is_beginner_friendly': data['is_beginner_friendly'],
                'recommended_sets': data['recommended_sets'],
                'recommended_reps': data['recommended_reps'],
                'recommended_duration': data['recommended_duration'],
                'recommended_rest': data['recommended_rest'],
                'description': data['description'],
                'instructions': data['instructions'],
                'beginner_tips': data['beginner_tips'],
            }

            # Shared exercises stay gender_category='all'; new ones are 'female'
            if not is_shared:
                defaults['gender_category'] = 'female'
            # For shared exercises, don't override gender_category —
            # keep it 'all' so all users see them.

            try:
                exercise, was_created = Exercise.objects.update_or_create(
                    name=name,
                    defaults=defaults,
                )
                if was_created:
                    created_count += 1
                else:
                    updated_count += 1
            except Exception as exc:
                self.stderr.write(self.style.WARNING(
                    f'Skipped "{name}": {exc}'
                ))

        self.stdout.write(self.style.SUCCESS(
            f'Women\'s Fitness library ready: '
            f'{created_count} new exercises, '
            f'{updated_count} updated. '
            f'Total in database: {Exercise.objects.count()}.'
        ))
