# Generated by Django 6.1 on 2026-08-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_workout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='body_part',
            field=models.CharField(default='Full Body', max_length=40),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='exercise_seconds',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
