# Generated by Django 6.1 on 2026-08-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_exercise_body_part_workoutexercise_exercise_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='equipment_type',
            field=models.CharField(choices=[('bodyweight', 'Bodyweight'), ('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('kettlebell', 'Kettlebell'), ('cable', 'Cable'), ('machine', 'Machine'), ('plate', 'Plate-loaded'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
