# Generated by Django 6.1 on 2026-08-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_exercise_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
    ]
