# Generated by Django 6.1 on 2026-08-26 06:16

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_workoutset_skipped'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exercise',
            name='unique_exercise_category',
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_exercise_name_ci'),
        ),
    ]
