# Generated by Django 6.1 on 2026-08-26 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_remove_exercise_unique_exercise_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not', 'Prefer not to say')], default='prefer_not', max_length=20)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('goal', models.CharField(choices=[('bulk', 'Build Muscle / Bulk'), ('cut', 'Lose Fat / Cut'), ('maintain', 'Maintain Weight'), ('strength', 'Build Strength'), ('fitness', 'General Fitness')], default='fitness', max_length=20)),
                ('workout_location', models.CharField(choices=[('gym', 'Gym'), ('home', 'Home')], default='home', max_length=10)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('workout_preference', models.CharField(choices=[('strength', 'Strength'), ('muscle', 'Muscle Building'), ('fat_loss', 'Fat Loss'), ('calisthenics', 'Calisthenics'), ('cardio', 'Cardio'), ('full_body', 'Full Body'), ('mixed', 'Mixed Training')], default='mixed', max_length=20)),
                ('home_equipment', models.JSONField(blank=True, default=list)),
                ('profile_completed', models.BooleanField(default=False)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_workout_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
