# Generated by Django 6.1 on 2026-08-26 08:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='workout_preference',
        ),
        migrations.CreateModel(
            name='DailyDietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('goal', models.CharField(max_length=20)),
                ('breakfast', models.CharField(max_length=255)),
                ('morning_snack', models.CharField(max_length=255)),
                ('lunch', models.CharField(max_length=255)),
                ('evening_snack', models.CharField(max_length=255)),
                ('dinner', models.CharField(max_length=255)),
                ('hydration', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_diet_plan')],
            },
        ),
    ]
