# Generated by Django 6.1 on 2026-08-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_remove_userprofile_workout_preference_dailydietplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('morning_snack', 'Mid-morning snack'), ('lunch', 'Lunch'), ('evening_snack', 'Evening snack'), ('dinner', 'Dinner'), ('hydration', 'Hydration')], max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('description', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=500)),
                ('goal', models.CharField(default='all', max_length=20)),
                ('day_of_week', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('meal_type', 'goal', 'day_of_week'), name='unique_diet_meal_slot')],
            },
        ),
    ]
