# Generated by Django 6.1 on 2026-08-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0010_dietmeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment_type',
            field=models.CharField(choices=[('bodyweight', 'Bodyweight'), ('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('kettlebell', 'Kettlebell'), ('cable', 'Cable'), ('machine', 'Machine'), ('resistance_band', 'Resistance band'), ('pullup_bar', 'Pull-up bar'), ('bench', 'Bench'), ('plate', 'Plate-loaded'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
