# Generated by Django 6.1 on 2026-08-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0011_alter_exercise_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
