# Generated by Django 6.1 on 2026-08-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0012_workout_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='gender_category',
            field=models.CharField(choices=[('all', 'All'), ('female', 'Female'), ('male', 'Male')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_beginner_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='recommended_duration',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='exercise',
            name='recommended_reps',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='exercise',
            name='recommended_rest',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='exercise',
            name='recommended_sets',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment_type',
            field=models.CharField(choices=[('bodyweight', 'Bodyweight'), ('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('kettlebell', 'Kettlebell'), ('cable', 'Cable'), ('machine', 'Machine'), ('resistance_band', 'Resistance band'), ('pullup_bar', 'Pull-up bar'), ('bench', 'Bench'), ('plate', 'Plate-loaded'), ('step', 'Step / Platform'), ('jump_rope', 'Jump Rope'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
