# Generated by Django 6.1 on 2026-08-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0013_exercise_difficulty_exercise_gender_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
