# Generated by Django 6.1 on 2026-08-27

from django.db import migrations, models


def clear_retired_gender_value(apps, schema_editor):
    UserProfile = apps.get_model('workout', 'UserProfile')
    # Do not guess a user's gender.  Existing retired values become neutral
    # until the user chooses Male or Female in their profile.
    UserProfile.objects.filter(gender='prefer_not').update(gender=None)


def restore_retired_gender_value(apps, schema_editor):
    UserProfile = apps.get_model('workout', 'UserProfile')
    UserProfile.objects.filter(gender__isnull=True).update(gender='prefer_not')


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0014_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default=None, max_length=20, null=True),
        ),
        migrations.RunPython(clear_retired_gender_value, restore_retired_gender_value),
    ]
