"""
Comprehensive exercise detail information for all 94 male exercises.
Contains unique descriptions, numbered step-by-step performance instructions (4-6 steps),
exercise-specific beginner tips, and relevant recommended workout parameters (sets, reps/duration, rest).
"""

MALE_EXERCISE_DETAILS = {
    'Arch Hold': {
        'description': 'Arch Hold is a foundational gymnastics and calisthenics static hold that strengthens the posterior chain, including the lower back, glutes, hamstrings, and upper back postural muscles.',
        'instructions': '1. Lie face down on a mat with your legs straight and arms extended overhead.\n2. Squeeze your glutes and press your hips firmly into the floor.\n3. Simultaneously lift your chest, shoulders, arms, and legs a few inches off the ground.\n4. Keep your neck neutral by gazing slightly forward and downward.\n5. Hold the arched position steadily while maintaining steady, controlled breathing.\n6. Lower back down with control once the target duration is reached.',
        'beginner_tips': 'Do not overarch by throwing your head back; focus on engaging your glutes and upper back rather than pinching your lower spine.',
        'recommended_sets': '3',
        'recommended_reps': '',
        'recommended_duration': '30–45 seconds',
        'recommended_rest': '60 seconds',
    },
    'Arnold Press': {
        'description': 'The Arnold Press is a dynamic shoulder exercise popularized by Arnold Schwarzenegger that rotates the dumbbells through a full range of motion to recruit all three deltoid heads and improve overhead stability.',
        'instructions': '1. Sit on an upright bench holding a dumbbell in each hand at chin height with palms facing your chest.\n2. Brace your core and maintain a flat back against the backrest.\n3. Press the dumbbells upward while rotating your wrists outward so your palms face forward at the top.\n4. Fully extend your arms overhead without aggressively locking out your elbows.\n5. Reverse the rotational movement slowly to lower the weights back to the starting chin level.\n6. Pause briefly before initiating the next repetition.',
        'beginner_tips': 'Use lighter dumbbells than you would for standard overhead presses until the wrist and shoulder rotation feels natural and fluid.',
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
    'Back Lever': {
        'description': 'Back Lever is an advanced calisthenics static hold performed on a pull-up bar or gymnastics rings, building exceptional straight-arm pulling strength, shoulder flexibility, and full-body tension.',
        'instructions': '1. Hang from a sturdy pull-up bar or gymnastics rings with an overhand grip.\n2. Invert your body by bringing your knees toward your chest and passing your feet through your arms.\n3. Extend your legs backwards and lower your torso until your entire body is parallel to the ground.\n4. Point your toes, squeeze your glutes, and lock out your elbows completely.\n5. Hold the horizontal position while depressing and protracting your shoulder blades.\n6. Tuck your knees back to your chest to safely exit the movement.',
        'beginner_tips': 'Master tucked back levers and build thorough bicep tendon conditioning before attempting a full straight-leg back lever.',
        'recommended_sets': '3–4',
        'recommended_reps': '',
        'recommended_duration': '10–20 seconds',
        'recommended_rest': '90 seconds',
    },
    'Back Squat': {
        'description': 'The Barbell Back Squat is a premier compound lower-body lift that builds maximal strength and muscular development across the quadriceps, glutes, hamstrings, and spinal erectors.',
        'instructions': '1. Position a barbell across your upper back and traps, gripping the bar firmly with hands slightly wider than shoulders.\n2. Unrack the bar, step back, and set your feet shoulder-width apart with toes slightly flared.\n3. Take a deep breath into your belly, brace your core, and push your hips back while bending your knees.\n4. Lower until your hips sink below parallel with your knees, keeping your chest proud.\n5. Drive firmly through your whole foot to reverse the movement and stand up.\n6. Exhale as you lock out your hips and reset your brace for the next rep.',
        'beginner_tips': 'Keep your chest elevated and ensure your knees track in line with your toes rather than caving inward as you rise from the bottom.',
        'recommended_sets': '3',
        'recommended_reps': '8–10',
        'recommended_duration': '',
        'recommended_rest': '90 seconds',
    },
    'Band Bicep Curl': {
        'description': 'Band Bicep Curl uses elastic resistance to isolate the biceps, providing ascending tension that peaks at full elbow flexion for joint-friendly arm strengthening.',
        'instructions': '1. Stand on the center of a resistance band with your feet hip-width apart, holding an end in each hand.\n2. Stand tall with your chest up, shoulders pinned back, and elbows tucked tight against your ribs.\n3. Curl your hands upward toward your shoulders by contracting your biceps.\n4. Squeeze your biceps hard at the peak of the movement where band tension is highest.\n5. Slowly lower your hands back down under control to fully extend your arms.\n6. Maintain constant tension without letting the band snap your arms downward.',
        'beginner_tips': 'Keep your elbows glued to your sides throughout the movement to prevent your front shoulders from taking over the work.',
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
    },
    'Band Chest Press': {
        'description': 'Band Chest Press is an accessible horizontal pushing exercise that uses resistance bands to build chest, front deltoid, and tricep strength with smooth, progressive resistance.',
        'instructions': '1. Anchor a resistance band securely behind you at chest height or wrap it across your upper back.\n2. Hold the handles with an overhand grip and take a staggered stance for stability.\n3. Position your hands near your armpits with elbows bent at roughly 45 degrees.\n4. Press both hands forward horizontally until your arms are fully extended in front of your chest.\n5. Squeeze your pectoral muscles firmly at the peak of the press.\n6. Slowly return your hands to the starting position under control.',
        'beginner_tips': 'Maintain a firm core brace and avoid leaning too far forward as you press against the band tension.',
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
    },
    'Band Glute Bridge': {
        'description': 'Band Glute Bridge places a resistance band across the thighs or hips to increase gluteus medius and maximus activation, enhancing hip extension power and knee stability.',
        'instructions': '1. Place a looped resistance band around your thighs just above your knees.\n2. Lie flat on your back with knees bent and feet planted flat on the floor, hip-width apart.\n3. Press your knees slightly outward against the band to engage your outer glutes.\n4. Drive through your heels and lift your hips toward the ceiling until your thighs and torso form a straight line.\n5. Squeeze your glutes tightly at the top for one to two seconds.\n6. Lower your hips back to the mat with control without letting your knees cave inward.',
        'beginner_tips': 'Do not hyperextend your lower back at the top; drive purely from your hips and glutes while keeping your ribs drawn down.',
        'recommended_sets': '3',
        'recommended_reps': '15–20',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
    },
    'Band Lateral Raise': {
        'description': 'Band Lateral Raise targets the lateral deltoids using constant tension to develop shoulder width, muscular definition, and joint stability with minimal joint impact.',
        'instructions': '1. Stand on the middle of a resistance band with feet hip-width apart, holding the ends by your sides.\n2. Maintain a slight bend in your knees, tall posture, and a slight bend in your elbows.\n3. Raise your arms out to the sides in a wide arc until your hands reach shoulder height.\n4. Lead with your elbows and keep your palms facing the floor at the peak.\n5. Pause briefly at shoulder height while feeling the lateral shoulder contraction.\n6. Lower your arms slowly against the band resistance back to your thighs.',
        'beginner_tips': 'Avoid shrugging your neck or using momentum to bounce the band upward; keep your upper traps relaxed.',
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
    },
    'Band Row': {
        'description': 'Band Row strengthens the lats, rhomboids, rear delts, and middle trapezius, improving posture and upper-body pulling strength using elastic tension.',
        'instructions': '1. Anchor the band securely at chest or waist height, or loop it around your feet while seated with legs extended.\n2. Hold the band handles with palms facing each other and sit or stand with a flat, upright spine.\n3. Pull your shoulder blades back and down before bending your elbows.\n4. Row your elbows straight back along your ribs until your hands reach your abdomen.\n5. Squeeze your shoulder blades together firmly at the end of the pull.\n6. Slowly extend your arms forward to return to the starting stretch.',
        'beginner_tips': 'Focus on pulling your elbows backwards rather than simply curling with your wrists and forearms.',
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
    },
    'Band Shoulder Press': {
        'description': 'Band Shoulder Press develops vertical pushing strength and overhead shoulder stability by engaging the deltoids, upper chest, and triceps with progressive band resistance.',
        'instructions': '1. Stand firmly on the center of a resistance band and bring the handles to shoulder height with palms forward.\n2. Set your feet hip-width apart, tuck your pelvis slightly, and brace your abdominal wall.\n3. Press the band handles straight overhead until your arms are fully extended.\n4. Keep your wrists stacked directly over your elbows throughout the upward path.\n5. Squeeze your shoulders at the top without arching your lower back.\n6. Slowly lower the handles back down to collarbone height under steady control.',
        'beginner_tips': 'If the resistance is too heavy to press without arching your spine, step onto the band with only one foot.',
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
    },
    'Band Squat': {
        'description': 'Band Squat reinforces sound squat mechanics and builds lower-body power by adding accommodating resistance across the quadriceps, glutes, and hips.',
        'instructions': '1. Stand on the center of a resistance band with feet shoulder-width apart and loop the top over your shoulders or hold at chest level.\n2. Keep your chest high, gaze forward, and brace your midsection firmly.\n3. Push your hips back and bend your knees to lower into a deep, controlled squat.\n4. Descend until your thighs are at least parallel to the floor.\n5. Drive forcefully through your heels and midfoot against the increasing band tension.\n6. Stand tall and squeeze your glutes at the top before repeating.',
        'beginner_tips': 'Ensure the band remains secure under your midfoot and maintain an upright torso as tension increases near the top.',
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
    },
    'Band Tricep Extension': {
        'description': 'Band Tricep Extension isolates the three heads of the triceps brachii, utilizing elastic tension to strengthen arm lockout strength and tone the back of the arms.',
        'instructions': '1. Anchor a resistance band high overhead or hold one end behind your back with the opposite hand.\n2. Grip the free end with your working arm, pinning your elbow in place beside your head or ribs.\n3. Extend your arm by straightening your elbow and contracting your tricep.\n4. Squeeze your tricep forcefully at full arm extension.\n5. Slowly bend your elbow to return to the starting stretch without moving your upper arm.\n6. Repeat smoothly for all prescribed repetitions before switching arms if working unilaterally.',
        'beginner_tips': 'Lock your upper arm completely stationary so all the movement comes from elbow extension alone.',
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
    },
    'Barbell Row': {
        'description': 'The Bent-Over Barbell Row is a fundamental compound back builder that develops thickness across the lats, traps, rhomboids, and lower back while enhancing hip-hinge endurance.',
        'instructions': '1. Stand with feet hip-width apart and grip a barbell with a shoulder-width overhand grip.\n2. Hinge at your hips with soft knees, lowering your torso to roughly a 45-degree angle with a flat back.\n3. Let the bar hang directly beneath your shoulders with arms fully extended.\n4. Pull the barbell toward your lower ribcage or upper waist by driving your elbows back.\n5. Squeeze your shoulder blades tightly together at the top of the contraction.\n6. Lower the barbell under control back to the starting hanging position.',
        'beginner_tips': 'Avoid standing up or using momentum from your hips to yank the bar; keep your torso fixed at the hinge angle.',
        'recommended_sets': '3',
        'recommended_reps': '8–10',
        'recommended_duration': '',
        'recommended_rest': '75–90 seconds',
    },
    'Bear Crawl': {
        'description': 'Bear Crawl is a full-body dynamic movement that challenges core stability, shoulder endurance, contralateral coordination, and hip mobility from a low quadruped position.',
        'instructions': '1. Start on all fours with hands stacked under your shoulders and knees under your hips.\n2. Tuck your toes and lift your knees just one to two inches off the floor.\n3. Maintain a flat back, engaged core, and stable pelvis.\n4. Move your right hand and left foot forward simultaneously in a small, controlled step.\n5. Follow immediately by moving your left hand and right foot forward.\n6. Continue crawling forward smoothly while keeping your hips low and level.',
        'beginner_tips': 'Do not let your hips rise into the air or sway side to side; keep your knees hovering just barely above the mat.',
        'recommended_sets': '3',
        'recommended_reps': '',
        'recommended_duration': '30–45 seconds',
        'recommended_rest': '60 seconds',
    },
    'Bench Press': {
        'description': 'The Barbell Bench Press is the quintessential upper-body strength exercise, developing raw pressing power and muscle mass in the pectoralis major, anterior deltoids, and triceps.',
        'instructions': '1. Lie flat on the bench with your eyes directly beneath the racked barbell and feet planted firmly on the floor.\n2. Grip the barbell slightly wider than shoulder-width and retract your shoulder blades into the bench.\n3. Unrack the bar and stabilize it directly over your chest with straight arms.\n4. Lower the barbell under control to lightly touch your mid-chest, keeping elbows tucked at 45 to 70 degrees.\n5. Press the bar upward with power by driving through your chest and triceps back to the starting point.\n6. Lock out smoothly overhead and maintain upper-back tightness for the next rep.',
        'beginner_tips': 'Keep your shoulder blades pulled back and down into the bench throughout the entire set to protect your shoulder joints.',
        'recommended_sets': '3',
        'recommended_reps': '8–10',
        'recommended_duration': '',
        'recommended_rest': '90 seconds',
    },
    'Bicep Curl': {
        'description': 'The Dumbbell Bicep Curl is an iconic arm isolation exercise that trains elbow flexion, building strength, shape, and definition in the biceps brachii and brachialis.',
        'instructions': '1. Stand tall holding a dumbbell in each hand at your sides with palms facing inward and core braced.\n2. Pin your upper arms to the sides of your torso and keep your shoulders relaxed.\n3. Curl the dumbbells upward while supinating your forearms so your palms face your shoulders near the top.\n4. Squeeze your biceps firmly at the peak contraction for one second.\n5. Lower the dumbbells slowly back to full arm extension along your thighs.\n6. Repeat smoothly without swinging your torso.',
        'beginner_tips': 'Do not let your elbows drift forward or swing your lower back to heave the weights upward; lift with pure bicep force.',
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
    'Bicycle Crunch': {
        'description': 'Bicycle Crunch is a high-yield dynamic core movement that activates the rectus abdominis and obliques through rotational flexion and rhythmic contralateral leg extension.',
        'instructions': '1. Lie on your back with your hands lightly touching behind your head and knees lifted at 90 degrees.\n2. Press your lower back firmly into the floor and lift your shoulder blades off the mat.\n3. Rotate your torso to bring your right elbow toward your left knee while extending your right leg straight out.\n4. Pause briefly to contract your oblique muscles.\n5. Switch sides smoothly by drawing your right knee in, extending your left leg, and rotating your left elbow across.\n6. Continue alternating in a steady, controlled cycling rhythm.',
        'beginner_tips': 'Do not yank on your neck with your hands; turn from your ribcage and shoulders while keeping your elbows wide.',
        'recommended_sets': '3',
        'recommended_reps': '16–20 total',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
    },
    'Bird Dog': {
        'description': 'Bird Dog is a restorative core stability and motor-control exercise that strengthens the lumbar erectors, glutes, and shoulders while teaching neutral spine preservation.',
        'instructions': '1. Begin on your hands and knees in a tabletop position with hands under shoulders and knees under hips.\n2. Brace your midsection and establish a flat, neutral spine.\n3. Simultaneously reach your right arm straight forward and kick your left leg straight back.\n4. Hold the extended position for a full second, aligning your arm, torso, and leg in one straight line.\n5. Slowly return your hand and knee to the tabletop position.\n6. Repeat the movement on the opposite side with your left arm and right leg.',
        'beginner_tips': 'Keep your hips perfectly level with the floor; imagine balancing a glass of water on your lower back.',
        'recommended_sets': '3',
        'recommended_reps': '10–12 each side',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
    },
    'Bulgarian Split Squat': {
        'description': 'The Bulgarian Split Squat is an intense unilateral lower-body exercise that develops exceptional single-leg strength, balance, hip mobility, and quadricep/glute hypertrophy.',
        'instructions': '1. Stand about two feet in front of a sturdy bench or chair and place the top of your rear foot onto the surface.\n2. Keep your torso upright and your front foot planted firmly on the floor.\n3. Lower your hips straight down by bending your front knee until your front thigh is parallel to the ground.\n4. Allow your rear knee to descend naturally toward the floor just above the mat.\n5. Drive firmly through your front heel and midfoot to return to the top standing position.\n6. Complete all repetitions on one side before switching legs.',
        'beginner_tips': 'Place most of your body weight on your front leg; the back leg is merely there to provide balance support.',
        'recommended_sets': '3',
        'recommended_reps': '8–10 each leg',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
    'Burpees': {
        'description': 'Burpees are a high-intensity bodyweight conditioning movement combining a squat, push-up, and vertical jump to elevate heart rate and build full-body muscular endurance.',
        'instructions': '1. Stand tall with your feet shoulder-width apart and arms at your sides.\n2. Drop into a squat and plant your hands flat on the floor in front of your feet.\n3. Jump your feet backward into a straight-arm plank position.\n4. Lower your chest to the floor in a quick, controlled push-up.\n5. Press back up and immediately hop your feet back forward outside your hands.\n6. Explosively jump straight up into the air, reaching your hands overhead, and land softly.',
        'beginner_tips': 'Step back and step forward instead of jumping if you are building up joint tolerance or managing fatigue.',
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
    'Cable Crossover': {
        'description': 'Cable Crossover delivers continuous tension across the pectoral muscles throughout the entire range of motion, enhancing inner-chest contraction and muscular definition.',
        'instructions': '1. Set cable pulleys at high or shoulder level and attach single D-handles to each side.\n2. Grip the handles, step forward into a staggered stance, and lean your torso slightly forward.\n3. Keep a slight, fixed bend in your elbows and open your arms wide to feel a stretch across your chest.\n4. Bring your hands together in a downward and forward hugging motion until they meet in front of your hips or chest.\n5. Squeeze your pectoral muscles intensely at peak contraction for one second.\n6. Slowly reverse the motion to allow a full, controlled chest stretch.',
        'beginner_tips': 'Maintain a rigid elbow angle throughout the movement; do not turn the fly into a pressing motion.',
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
    'Calf Raise': {
        'description': 'Calf Raise isolates the gastrocnemius and soleus muscles of the lower leg, increasing ankle stability, jumping power, and lower-leg muscular definition.',
        'instructions': '1. Stand tall with the balls of your feet on a raised step or flat ground with feet hip-width apart.\n2. Hold onto a wall or sturdy support for balance if needed.\n3. Lower your heels slightly below the step level to feel a deep stretch in your calves.\n4. Drive forcefully through the balls of your feet to raise your heels as high as possible.\n5. Squeeze your calf muscles tightly at the top of the contraction for one second.\n6. Lower your heels back down smoothly under control.',
        'beginner_tips': 'Avoid bouncing at the bottom of the movement; pause briefly at full stretch to eliminate Achilles tendon bounce.',
        'recommended_sets': '3',
        'recommended_reps': '15–20',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
    },
    'Chest Fly': {
        'description': 'Chest Fly isolates the pectoralis major through horizontal adduction, expanding chest flexibility and strengthening muscle fibers across the outer and inner chest.',
        'instructions': '1. Lie flat on a bench holding dumbbells or cables directly over your chest with palms facing each other.\n2. Set a slight bend in your elbows and keep your shoulder blades pinched back.\n3. Lower your arms out to the sides in a wide arc until you feel a comfortable stretch across your chest.\n4. Stop when your elbows reach roughly bench or chest depth.\n5. Contract your chest muscles to bring the weights back together along the same wide arc.\n6. Squeeze your chest at the top without allowing the weights to clash together.',
        'beginner_tips': 'Never lower the weights below shoulder level if you feel excessive pulling in your front shoulder capsule.',
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
    'Chin-Up': {
        'description': 'The Chin-Up is a potent upper-body compound pull using an underhand (supinated) grip that heavily recruits the lats, biceps, and forearms to pull your bodyweight above the bar.',
        'instructions': '1. Grip a pull-up bar with an underhand grip (palms facing you) shoulder-width apart.\n2. Hang at full arm extension with your core braced and legs straight or crossed.\n3. Pull your shoulder blades down and drive your elbows toward your hips.\n4. Pull your body upward until your chin clears the top of the bar.\n5. Pause briefly at the top to feel your lats and biceps contract.\n6. Lower yourself slowly all the way down to a complete, dead-hang stretch.',
        'beginner_tips': 'Avoid kicking your legs or swinging for momentum; focus on pulling purely through your biceps and upper back.',
        'recommended_sets': '3',
        'recommended_reps': '6–10',
        'recommended_duration': '',
        'recommended_rest': '90 seconds',
    },
    'Clean and Press': {
        'description': 'Clean and Press is an explosive full-body Olympic-style movement that builds total-body power, coordination, and muscular endurance from the floor to overhead.',
        'instructions': '1. Stand with feet hip-width apart and a weight placed on the floor in front of you.\n2. Hinge at your hips and bend your knees to grip the weight with a flat spine.\n3. Explosively extend your hips and knees to pull the weight upward along your body.\n4. Snap your elbows underneath to catch the weight at shoulder height in a front rack position.\n5. Dip your knees slightly and press the weight forcefully straight overhead to full lockout.\n6. Lower the weight under control back to your shoulders, then to your hips and floor.',
        'beginner_tips': 'Master the hip-hinge clean and the overhead press separately before combining them into a continuous fluid movement.',
        'recommended_sets': '3',
        'recommended_reps': '5–8',
        'recommended_duration': '',
        'recommended_rest': '90–120 seconds',
    },
    'Close-Grip Push-Up': {
        'description': 'Close-Grip Push-Up shifts the mechanical emphasis of the classic push-up toward the triceps and inner chest by narrowing hand placement.',
        'instructions': '1. Set up in a high plank position with your hands placed directly under your chest, closer than shoulder-width.\n2. Keep your body in a rigid straight line from head to heels with glutes and abs engaged.\n3. Lower your chest toward your hands while keeping your elbows tucked tight against your ribcage.\n4. Descend until your chest is just an inch above the floor.\n5. Press firmly through the palms of your hands to push back to full arm extension.\n6. Squeeze your triceps at the top before beginning the next repetition.',
        'beginner_tips': 'Keep your elbows glued against your sides rather than flaring them out to place maximal work on your triceps.',
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
    'Concentration Curl': {
        'description': 'Concentration Curl isolates the bicep peak by bracing the upper arm against the inner thigh, removing all torso momentum for strict, targeted arm hypertrophy.',
        'instructions': '1. Sit on a bench with your legs spread and hold a dumbbell in one hand.\n2. Rest the back of your upper arm firmly against your inner thigh on the same side.\n3. Let the dumbbell hang down toward the floor with your arm fully extended.\n4. Curl the dumbbell upward toward your face while keeping your upper arm completely still.\n5. Squeeze your bicep forcefully at peak elbow flexion for one count.\n6. Lower the weight slowly back to the starting stretch before repeating.',
        'beginner_tips': 'Do not lean your upper body backward as you curl; keep your torso fixed and let your bicep do 100% of the lifting.',
        'recommended_sets': '3',
        'recommended_reps': '10–12 each arm',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
    },
    'Crunch': {
        'description': 'The Crunch is a focused abdominal isolation movement that flexes the thoracic spine to target the upper and middle fibers of the rectus abdominis.',
        'instructions': '1. Lie on your back with your knees bent and feet flat on the floor, hip-width apart.\n2. Place your fingertips lightly behind your ears or cross your arms over your chest.\n3. Press your lower back into the floor and draw your navel toward your spine.\n4. Contract your abdominals to curl your head, neck, and shoulder blades off the floor.\n5. Exhale and hold the peak contraction at the top for one second.\n6. Slowly lower your shoulder blades back down to the mat without resting completely.',
        'beginner_tips': 'Do not interlace your fingers behind your head or pull on your neck; lead the movement by contracting your ribs toward your hips.',
        'recommended_sets': '3',
        'recommended_reps': '15–20',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
    },
    'Cycling': {
        'description': 'Cycling is a premier low-impact cardiovascular exercise that builds aerobic fitness, burns calories, and strengthens the quadriceps, hamstrings, and calves without joint impact.',
        'instructions': '1. Adjust the bike seat height so there is a slight bend in your knee at the bottom of the pedal stroke.\n2. Grip the handlebars lightly, engage your core, and keep your shoulders relaxed.\n3. Begin pedaling at a smooth, consistent cadence, pushing down with your midfoot and pulling up smoothly.\n4. Maintain an upright or athletic forward posture without rounding your lower back.\n5. Breathe rhythmically through your nose and mouth to match your training intensity.\n6. Cool down by reducing resistance and pedaling at an easy pace for the final few minutes.',
        'beginner_tips': 'Avoid rocking your hips side to side on the saddle; keep your pelvis stable and drive evenly through both legs.',
        'recommended_sets': '1',
        'recommended_reps': '',
        'recommended_duration': '20–30 minutes',
        'recommended_rest': 'As needed',
    },
    'Dead Bug': {
        'description': 'Dead Bug is an essential core stabilization exercise that teaches anterior pelvic control and core bracing while moving contralateral limbs without lumbar extension.',
        'instructions': '1. Lie on your back with your arms reaching straight toward the ceiling and knees bent at 90 degrees over your hips.\n2. Flatten your lower back firmly against the floor so there is zero gap under your spine.\n3. Slowly lower your right arm overhead and extend your left leg straight out toward the floor.\n4. Hover both limbs just above the floor without letting your lower back arch off the mat.\n5. Bring your right arm and left leg back to the starting 90-degree position.\n6. Repeat the movement smoothly with your left arm and right leg.',
        'beginner_tips': 'If your lower back begins to arch off the floor, shorten your leg reach until your core strength improves.',
        'recommended_sets': '3',
        'recommended_reps': '10–12 each side',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
    },
    'Dead Hang': {
        'description': 'Dead Hang is a powerful isometric grip and shoulder decompression exercise that increases grip strength, decompresses the spine, and improves shoulder mobility.',
        'instructions': '1. Reach up and grip a pull-up bar with an overhand grip roughly shoulder-width apart.\n2. Step off the platform or bench to allow your body to hang completely freely.\n3. Keep your arms straight and relax your spine to allow natural spinal decompression.\n4. Engage your core lightly to prevent excessive swinging.\n5. Breathe deeply and hold the hanging position for the desired duration.\n6. Carefully step back onto the platform before releasing your grip.',
        'beginner_tips': 'Start with shorter hold times of 15 to 20 seconds and focus on relaxing your breathing while maintaining a secure grip.',
        'recommended_sets': '3',
        'recommended_reps': '',
        'recommended_duration': '30–60 seconds',
        'recommended_rest': '60 seconds',
    },
    'Deadlift': {
        'description': 'The Barbell Deadlift is a premier total-body strength compound movement that trains the entire posterior chain, including the hamstrings, glutes, lower back, lats, and forearms.',
        'instructions': '1. Stand with feet hip-width apart and the barbell over your midfoot, roughly an inch from your shins.\n2. Hinge at your hips and grip the bar just outside your legs with an overhand or mixed grip.\n3. Lower your hips, pull your chest up, and pull the slack out of the barbell.\n4. Drive forcefully through the floor with your legs, keeping the bar close to your shins.\n5. Stand fully upright by extending your hips and knees simultaneously, squeezing your glutes at the top.\n6. Hinge at the hips to lower the bar back to the floor along the same tight vertical path.',
        'beginner_tips': 'Never let your lower back round over during the pull; keep your spine flat, lats locked in, and drive through your heels.',
        'recommended_sets': '3',
        'recommended_reps': '5–8',
        'recommended_duration': '',
        'recommended_rest': '90–120 seconds',
    },
    'Decline Bench Press': {
        'description': 'The Decline Bench Press angles the torso downward to target the lower fibers of the pectoralis major with reduced shoulder joint stress and high pressing leverage.',
        'instructions': '1. Secure your legs firmly into the decline bench pads and lie back flat on the decline bench.\n2. Grip the barbell with an overhand grip slightly wider than shoulder-width.\n3. Unrack the bar and steady it directly over your lower chest with arms locked.\n4. Lower the barbell under control until it lightly touches your lower pectoral line.\n5. Press the bar upward and slightly back toward the rack by driving through your chest and triceps.\n6. Lock out your arms smoothly before starting the next rep.',
        'beginner_tips': 'Always secure your ankles firmly into the bench rollers before unracking the barbell to ensure total stability.',
        'recommended_sets': '3',
        'recommended_reps': '8–10',
        'recommended_duration': '',
        'recommended_rest': '90 seconds',
    },
    'Decline Push-Up': {
        'description': 'Decline Push-Up elevates the feet to shift more bodyweight onto the upper chest, anterior deltoids, and triceps, creating a challenging bodyweight pressing angle.',
        'instructions': '1. Place your toes on a sturdy bench or box and place your hands flat on the floor shoulder-width apart.\n2. Establish a rigid plank line from your heels through your hips to your shoulders.\n3. Lower your chest toward the floor by bending your elbows at a 45-degree angle.\n4. Descend until your nose or chest is just an inch above the mat.\n5. Press powerfully into the floor to return to full arm extension.\n6. Keep your core and glutes squeezed tight to prevent your hips from sagging.',
        'beginner_tips': 'Start with a low elevation like a single step before moving to higher benches as your upper chest strength develops.',
        'recommended_sets': '3',
        'recommended_reps': '10–15',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
    'Diamond Push-Up': {
        'description': 'Diamond Push-Up places the hands together in a diamond shape directly beneath the chest to maximize tricep muscle activation and inner chest engagement.',
        'instructions': '1. Assume a standard push-up plank position with your feet together or hip-width apart.\n2. Place your hands together on the floor directly beneath your sternum, touching your thumbs and index fingers to form a diamond.\n3. Brace your core and maintain a straight line from your head to your heels.\n4. Lower your chest down until it lightly touches the back of your hands.\n5. Push through your palms to return to full arm extension, focusing on your triceps.\n6. Squeeze your triceps at the top of the movement.',
        'beginner_tips': 'If the diamond hand placement strains your wrists, widen your hands slightly until your wrist joints feel comfortable.',
        'recommended_sets': '3',
        'recommended_reps': '8–12',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
    'Dips': {
        'description': 'Dips are a powerhouse upper-body compound movement on parallel bars that builds massive pressing strength across the triceps, lower chest, and anterior deltoids.',
        'instructions': '1. Mount the parallel bars and lock your arms out with shoulders packed down and core tight.\n2. Lean your torso slightly forward to recruit more chest, or stay upright for more tricep emphasis.\n3. Lower your body under control by bending your elbows until they reach a 90-degree angle.\n4. Ensure your shoulders remain packed and do not roll forward at the bottom.\n5. Press through your palms to drive your body back up to full lockout.\n6. Pause briefly at the top before initiating the next repetition.',
        'beginner_tips': 'Do not dip deeper than a 90-degree elbow bend if you are new to the movement, as excessive depth can stress the anterior shoulder joint.',
        'recommended_sets': '3',
        'recommended_reps': '8–12',
        'recommended_duration': '',
        'recommended_rest': '75–90 seconds',
    },
    'Dumbbell Bench Press': {
        'description': 'The Dumbbell Bench Press allows independent arm movement and a deeper stretch than a barbell, correcting muscle imbalances while building the chest, shoulders, and triceps.',
        'instructions': '1. Sit on a flat bench with a dumbbell resting on each thigh.\n2. Lie back smoothly, using your knees to guide the dumbbells up over your chest.\n3. Set your feet flat on the floor and pull your shoulder blades together into the bench.\n4. Lower the dumbbells slowly down and slightly out to chest height, feeling a deep stretch.\n5. Press the dumbbells upward and slightly inward in an arc until arms are extended.\n6. Squeeze your chest at the top without banging the dumbbells together.',
        'beginner_tips': 'Keep your wrists straight and directly above your elbows throughout the entire pressing and lowering motion.',
        'recommended_sets': '3',
        'recommended_reps': '8–12',
        'recommended_duration': '',
        'recommended_rest': '75–90 seconds',
    },
    'Dumbbell Curl': {
        'description': 'The Dumbbell Curl provides free-moving arm isolation to build bicep size and grip strength, allowing natural wrist rotation to optimize bicep peak contraction.',
        'instructions': '1. Stand tall holding a dumbbell in each hand with arms extended and palms facing forward.\n2. Keep your chest elevated, shoulder blades retracted, and elbows tucked tight to your flanks.\n3. Curl the dumbbells upward toward your shoulders by contracting your biceps.\n4. Squeeze your biceps firmly at the top for one full second.\n5. Lower the dumbbells under control back to the starting hanging position.\n6. Fully straighten your arms at the bottom before beginning the next repetition.',
        'beginner_tips': 'Lower the dumbbells under a strict two-to-three second count to maximize muscle stimulation during the eccentric phase.',
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
    'Dumbbell Fly': {
        'description': 'The Dumbbell Fly isolates the pectoral muscles through horizontal adduction, stretching the chest under load to enhance muscle growth and chest width.',
        'instructions': '1. Lie flat on a bench with dumbbells held directly above your chest, palms facing each other.\n2. Establish a slight bend in your elbows and maintain this fixed elbow angle throughout.\n3. Lower the dumbbells out to the sides in a wide, sweeping arc until you feel a gentle chest stretch.\n4. Stop descending when your elbows reach the level of the bench.\n5. Contract your chest to bring the dumbbells back together along the same arc.\n6. Squeeze your pectorals tightly at the top without allowing the weights to touch.',
        'beginner_tips': 'Use moderate weights and avoid bending your elbows into a press; visualize hugging a large tree trunk.',
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
    'Dumbbell Row': {
        'description': 'The Single-Arm Dumbbell Row builds unilateral back strength, targeting the latissimus dorsi, rhomboids, and biceps while reinforcing core anti-rotational stability.',
        'instructions': '1. Place your left knee and left hand firmly on a flat bench with your back flat and parallel to the floor.\n2. Plant your right foot on the ground and hold a dumbbell in your right hand at full arm extension.\n3. Retract your right shoulder blade and pull the dumbbell up toward your hip.\n4. Drive your elbow high toward the ceiling and squeeze your lat at the top.\n5. Lower the dumbbell slowly back down to a full, controlled stretch.\n6. Complete all reps on one side before switching to the left arm.',
        'beginner_tips': 'Pull the dumbbell toward your hip pocket rather than straight up to your chest to maximize lat activation.',
        'recommended_sets': '3',
        'recommended_reps': '10–12 each arm',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
    'Dumbbell Shoulder Press': {
        'description': 'The Dumbbell Shoulder Press builds overhead pressing power and capped deltoids, allowing each arm to move freely to eliminate strength imbalances.',
        'instructions': '1. Sit on an upright bench with dumbbells at shoulder height, palms facing forward or slightly turned in.\n2. Plant your feet firmly on the floor and brace your abdominal wall.\n3. Press the dumbbells straight overhead until your arms are fully extended.\n4. Avoid arching your lower back away from the backrest as the weights rise.\n5. Lower the dumbbells smoothly back to ear/shoulder height under control.\n6. Pause briefly at the bottom before initiating the next repetition.',
        'beginner_tips': 'Keep your elbows angled slightly forward in the scapular plane (about 30 degrees) rather than flared directly out to the sides.',
        'recommended_sets': '3',
        'recommended_reps': '8–12',
        'recommended_duration': '',
        'recommended_rest': '75–90 seconds',
    },
    'Face Pull': {
        'description': 'The Cable Face Pull is an exceptional postural exercise that strengthens the rear deltoids, rhomboids, and rotator cuff muscles to balance pressing volume and protect shoulder health.',
        'instructions': '1. Attach a rope to a cable pulley set at eye or upper-chest height.\n2. Grip the rope ends with your thumbs pointing backward and step back to create tension.\n3. Stand tall with soft knees and an engaged core.\n4. Pull the center of the rope directly toward your bridge of the nose or forehead.\n5. Flare your elbows high and rotate your hands backward at the end of the pull.\n6. Squeeze your rear delts and upper back for a second, then return slowly to the start.',
        'beginner_tips': 'Focus on external shoulder rotation at the finish—your hands should end up higher than your elbows beside your ears.',
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '45–60 seconds',
    },
    'Front Lever': {
        'description': 'The Front Lever is an elite calisthenics isometric hold that requires extreme straight-arm lat strength, scapular depression, and total anterior core tension.',
        'instructions': '1. Hang from a pull-up bar with an overhand, shoulder-width grip.\n2. Engage your lats by pulling your straight arms down toward your hips.\n3. Lift your entire body horizontally until your torso, hips, and legs are parallel to the ground.\n4. Squeeze your glutes, point your toes, and lock out your elbows completely.\n5. Hold the horizontal plank position while breathing under high core tension.\n6. Lower your body smoothly back to a dead hang.',
        'beginner_tips': 'Train tucked front levers and advanced tuck variations extensively before progressing to single-leg or full lever holds.',
        'recommended_sets': '3–4',
        'recommended_reps': '',
        'recommended_duration': '10–20 seconds',
        'recommended_rest': '90 seconds',
    },
    'Front Raise': {
        'description': 'The Front Raise isolates the anterior deltoid head, improving forward shoulder elevation strength and upper-chest definition.',
        'instructions': '1. Stand tall with feet shoulder-width apart, holding weights resting against the front of your thighs.\n2. Keep a slight bend in your knees, an upright spine, and elbows softly unlocked.\n3. Raise the weights straight in front of your body until they reach eye or shoulder level.\n4. Pause briefly at the top to feel the front deltoids contract.\n5. Lower the weights back down slowly along the same path under strict control.\n6. Avoid swinging your hips or arching your lower back to hoist the load.',
        'beginner_tips': 'Use light weights and perform the lifting motion strictly from the shoulder joint without leaning back.',
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '45–60 seconds',
    },
    'Front Squat': {
        'description': 'The Front Squat places the barbell in a front-rack position across the anterior deltoids, requiring an upright torso that heavily targets the quadriceps and core stabilizers.',
        'instructions': '1. Rest the barbell across the front of your shoulders, holding it with clean grip fingertips or crossed arms.\n2. Keep your elbows driven high and parallel to the floor throughout the entire movement.\n3. Step back, set your feet shoulder-width apart, and brace your abdominal wall tightly.\n4. Squat down deeply by pushing your knees forward and hips down, maintaining a vertical chest.\n5. Descend until your hip crease is below the top of your knees.\n6. Drive through your midfoot to stand up, keeping your elbows elevated as you rise.',
        'beginner_tips': 'Never let your elbows drop down during the squat; keeping elbows high prevents the bar from rolling forward off your shoulders.',
        'recommended_sets': '3',
        'recommended_reps': '6–8',
        'recommended_duration': '',
        'recommended_rest': '90–120 seconds',
    },
    'Glute Bridge': {
        'description': 'The Glute Bridge is an accessible, effective hip-extension exercise that activates the gluteus maximus and hamstrings while teaching proper hip hinge mechanics.',
        'instructions': '1. Lie flat on your back with knees bent and feet planted hip-width apart on the floor, about 6 inches from your glutes.\n2. Rest your arms flat along the mat at your sides.\n3. Brace your core and flatten your lower back slightly into the floor.\n4. Drive through your heels to raise your hips toward the ceiling until thighs and torso align.\n5. Squeeze your glutes forcefully at the top for one to two seconds.\n6. Lower your hips back down smoothly to the floor.',
        'beginner_tips': 'Focus on pushing through your heels rather than your toes to maximize glute contraction over quadricep dominance.',
        'recommended_sets': '3',
        'recommended_reps': '15–20',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
    },
    'Goblet Squat': {
        'description': 'The Goblet Squat uses a single weight held at chest level to promote an upright torso, healthy squat depth, and excellent quadricep and hip development.',
        'instructions': '1. Stand tall holding a dumbbell or kettlebell vertically against your chest with both hands.\n2. Set your feet slightly wider than shoulder-width with toes turned out 15 to 30 degrees.\n3. Brace your midsection and pull your elbows down tight against your ribcage.\n4. Sit your hips back and down between your legs until your thighs reach parallel or below.\n5. Allow your elbows to track inside your knees at the bottom of the squat.\n6. Drive through the floor to return to standing, squeezing your glutes at the top.',
        'beginner_tips': 'Keep the weight glued to your sternum; letting it drift forward pulls your spine out of alignment.',
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
    'Handstand': {
        'description': 'The Handstand is a classic bodyweight skill that builds immense overhead shoulder stability, wrist strength, scapular elevation, and total-body balance.',
        'instructions': '1. Place your hands shoulder-width apart on the floor about six inches from a wall.\n2. Spread your fingers wide and grip the floor firmly with your fingertips.\n3. Kick up smoothly one leg at a time until your heels rest against the wall.\n4. Push actively through your shoulders, elevating your scapulae toward your ears.\n5. Squeeze your glutes, point your toes, and pull your ribs in to form a straight line.\n6. Step down one foot at a time with control to dismount.',
        'beginner_tips': 'Practice chest-to-wall handstands first to develop a straight body line before attempting back-to-wall kick-ups.',
        'recommended_sets': '3–4',
        'recommended_reps': '',
        'recommended_duration': '20–45 seconds',
        'recommended_rest': '60–90 seconds',
    },
    'Handstand Push-Up': {
        'description': 'The Handstand Push-Up is an elite calisthenics pressing exercise that builds extreme vertical pressing strength in the shoulders, upper chest, and triceps.',
        'instructions': '1. Kick up into a secure handstand against a sturdy wall with hands slightly wider than shoulder-width.\n2. Establish full body tension with feet against the wall and core engaged.\n3. Lower yourself by bending your elbows forward at a 45-degree angle toward your head.\n4. Descend until the crown of your head lightly touches the floor or an ab mat.\n5. Press forcefully through your palms and shoulders to drive back up to full arm extension.\n6. Lock out your arms and stabilize before performing the next repetition.',
        'beginner_tips': 'Do not flare your elbows out wide; tuck them forward slightly to create a stable tripod pressing base.',
        'recommended_sets': '3',
        'recommended_reps': '5–8',
        'recommended_duration': '',
        'recommended_rest': '90–120 seconds',
    },
    'Hanging Knee Raise': {
        'description': 'The Hanging Knee Raise develops the lower abdominals and hip flexors while decompressing the spine and enhancing grip and shoulder stability.',
        'instructions': '1. Hang from a pull-up bar with an overhand grip and arms fully extended.\n2. Engage your shoulders and core to eliminate swinging before starting.\n3. Draw your knees upward toward your chest by flexing your abs and hips.\n4. Curl your pelvis slightly upward at the top to fully contract your abdominal wall.\n5. Pause briefly with your knees tucked close to your chest.\n6. Lower your legs slowly and under control back to a straight hanging position.',
        'beginner_tips': 'Avoid using momentum or swinging your legs; perform the lift and the lowering phase under strict muscular control.',
        'recommended_sets': '3',
        'recommended_reps': '10–15',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
    'High Knees': {
        'description': 'High Knees is a dynamic bodyweight cardio drill that spikes heart rate, improves running cadence, and strengthens the hip flexors, core, and calves.',
        'instructions': '1. Stand tall with your feet hip-width apart and arms bent at 90 degrees by your sides.\n2. Drive your right knee up toward your chest while pumping your left arm forward.\n3. Quickly step down on the ball of your foot and immediately drive your left knee upward.\n4. Continue alternating knees at a rapid, rhythmic pace on the balls of your feet.\n5. Keep your chest high and engage your lower abdominals as each knee lifts.\n6. Land softly and maintain a quick, springy bounce.',
        'beginner_tips': 'Maintain an upright torso and avoid leaning backward as fatigue sets in; keep your weight slightly forward.',
        'recommended_sets': '3',
        'recommended_reps': '',
        'recommended_duration': '30–45 seconds',
        'recommended_rest': '45 seconds',
    },
    'Hip Thrust': {
        'description': 'The Hip Thrust is the premier glute-building exercise, providing maximum tension at full hip extension to build glute strength, power, and sprint speed.',
        'instructions': '1. Sit on the floor with your upper back supported against a bench and feet flat on the ground.\n2. Position your feet shoulder-width apart so your shins become vertical at the top of the lift.\n3. Drive through your heels and extend your hips upward toward the ceiling.\n4. Lift until your torso and thighs form a straight, horizontal tabletop line.\n5. Squeeze your glutes forcefully at the top while keeping your chin tucked.\n6. Lower your hips back toward the floor under control without losing core tension.',
        'beginner_tips': 'Keep your chin tucked toward your chest and look forward rather than tilting your head back to prevent lower back hyperextension.',
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '75–90 seconds',
    },
    'Hollow Body Hold': {
        'description': 'Hollow Body Hold is a fundamental gymnastics core exercise that builds total anterior core compression, spinal stability, and body tension.',
        'instructions': '1. Lie flat on your back on a mat with your legs extended straight and arms reaching overhead.\n2. Press your lower back completely flat against the mat by tilting your pelvis posteriorly.\n3. Lift your head, shoulders, arms, and straight legs two to four inches off the ground.\n4. Form a shallow banana shape with your body, keeping your core intensely engaged.\n5. Hold the position steadily while breathing in small, controlled breaths.\n6. Lower your limbs to rest once the target time is completed.',
        'beginner_tips': 'If your lower back lifts off the mat, bend your knees or bring your arms down by your sides until your core can maintain contact.',
        'recommended_sets': '3',
        'recommended_reps': '',
        'recommended_duration': '30–45 seconds',
        'recommended_rest': '45–60 seconds',
    },
    'Incline Bench Press': {
        'description': 'The Incline Barbell Bench Press targets the clavicular head of the pectoralis major (upper chest) and front deltoids, building upper-chest thickness and pressing power.',
        'instructions': '1. Lie on an incline bench set at 30 to 45 degrees with feet flat on the floor.\n2. Grip the barbell with an overhand grip slightly wider than shoulder-width.\n3. Unrack the barbell and stabilize it directly over your upper chest.\n4. Lower the bar smoothly until it touches your upper chest just below the collarbones.\n5. Drive the barbell straight upward by contracting your upper chest and triceps.\n6. Lock out smoothly at the top and reset your breath for the next repetition.',
        'beginner_tips': 'Do not set the bench incline too steep (above 45 degrees), as this shifts the majority of the workload from the chest onto the shoulders.',
        'recommended_sets': '3',
        'recommended_reps': '8–10',
        'recommended_duration': '',
        'recommended_rest': '90 seconds',
    },
    'Incline Dumbbell Press': {
        'description': 'The Incline Dumbbell Press builds upper chest volume and shoulder stability while allowing a natural wrist angle and balanced development between both sides.',
        'instructions': '1. Sit on an incline bench set to 30–45 degrees holding a dumbbell on each knee.\n2. Kick the dumbbells up to shoulder level as you lie back against the backrest.\n3. Plant your feet flat on the ground and pull your shoulder blades down and back.\n4. Lower the dumbbells slowly to upper-chest height, keeping elbows at a 45-degree angle.\n5. Press the weights up and slightly inward over your upper chest without clashing them together.\n6. Squeeze your upper chest at peak extension before lowering for the next rep.',
        'beginner_tips': 'Keep your wrists firm and stacked directly over your elbows rather than letting them bend backward.',
        'recommended_sets': '3',
        'recommended_reps': '8–12',
        'recommended_duration': '',
        'recommended_rest': '75–90 seconds',
    },
    'Incline Push-Up': {
        'description': 'The Incline Push-Up is an accessible bodyweight pressing regression that reduces the percentage of bodyweight lifted, perfect for building foundational chest and tricep strength.',
        'instructions': '1. Place your hands slightly wider than shoulder-width on an elevated bench, bar, or sturdy platform.\n2. Step your feet back until your body forms a straight line from your head to your heels.\n3. Brace your core and keep your glutes squeezed tight.\n4. Lower your chest toward the elevated edge by bending your elbows at a 45-degree angle.\n5. Push firmly through your palms to return to full arm extension.\n6. Repeat smoothly without allowing your lower back or hips to sag.',
        'beginner_tips': 'The higher the surface, the easier the push-up; lower the surface over time as your pressing strength increases.',
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '45–60 seconds',
    },
    'Jump Rope': {
        'description': 'Jump Rope is a high-efficiency conditioning exercise that sharpens footwork, improves calf and tendon elasticity, and burns calories rapidly.',
        'instructions': '1. Hold a jump rope handle in each hand with elbows close to your ribs and the rope behind your heels.\n2. Turn the rope using small, circular wrist rotations rather than large arm swings.\n3. Jump just one to two inches off the floor as the rope passes under your feet.\n4. Land softly on the balls of your feet with knees slightly unlocked.\n5. Maintain a steady, rhythmic bounce and breathe continuously.\n6. Continue for the prescribed time or rep count with a tall posture.',
        'beginner_tips': 'Jump only high enough for the thin rope to clear under your toes—stay light and springy on your feet.',
        'recommended_sets': '3',
        'recommended_reps': '',
        'recommended_duration': '60 seconds',
        'recommended_rest': '45 seconds',
    },
    'Jumping Jacks': {
        'description': 'Jumping Jacks are a classic full-body warm-up and cardiovascular movement that elevates heart rate, improves coordination, and warms up the shoulder and hip joints.',
        'instructions': '1. Stand upright with your feet together and arms resting comfortably at your sides.\n2. Jump your feet out slightly wider than shoulder-width while sweeping your arms overhead.\n3. Clap your hands lightly or bring them close together above your head.\n4. Immediately jump your feet back together while bringing your arms back to your sides.\n5. Land softly on the balls of your feet and maintain a continuous, fluid rhythm.\n6. Keep your core lightly braced and chest open throughout the exercise.',
        'beginner_tips': 'Land with soft, slightly bent knees on every rep to cushion your joints and protect your lower back.',
        'recommended_sets': '3',
        'recommended_reps': '',
        'recommended_duration': '45–60 seconds',
        'recommended_rest': '30–45 seconds',
    },
    'Kettlebell Swing': {
        'description': 'The Kettlebell Swing is an explosive hip-hinge exercise that builds ferocious posterior chain power across the hamstrings, glutes, core, and grip.',
        'instructions': '1. Stand with feet slightly wider than shoulder-width, with the kettlebell on the floor about a foot in front of you.\n2. Hinge at your hips, grip the kettlebell handle with both hands, and tilt it toward you.\n3. Hike the kettlebell back between your thighs like a football snap.\n4. Explosively snap your hips forward and stand tall, driving the kettlebell up to chest height.\n5. Let the bell float momentarily before guiding it back into the hip hinge.\n6. Repeat continuously in a powerful, rhythmic pendulum motion.',
        'beginner_tips': 'This is a hip hinge, not a squat; power the bell upward using rapid hip extension rather than lifting with your arms.',
        'recommended_sets': '3',
        'recommended_reps': '15–20',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
    'Knee Push-Up': {
        'description': 'The Knee Push-Up reduces resistance by placing the pivot point at the knees, allowing beginners to build chest, shoulder, and tricep strength with excellent form.',
        'instructions': '1. Start on your hands and knees with hands slightly wider than shoulder-width.\n2. Walk your knees back until your torso and thighs form a straight diagonal line.\n3. Tuck your pelvis and brace your core so your hips do not stick up in the air.\n4. Lower your chest toward the floor by bending your elbows back at roughly 45 degrees.\n5. Descend until your chest is an inch from the mat.\n6. Press firmly through your hands back to the starting straight-arm position.',
        'beginner_tips': 'Keep your hips aligned with your shoulders and knees—do not leave your hips behind in a tabletop position.',
        'recommended_sets': '3',
        'recommended_reps': '10–15',
        'recommended_duration': '',
        'recommended_rest': '45–60 seconds',
    },
    'L-Sit': {
        'description': 'The L-Sit is an iconic isometric core and gymnastics skill requiring intense abdominal compression, hip flexor endurance, and straight-arm scapular depression.',
        'instructions': '1. Place your hands on parallettes, dip bars, or flat on the floor beside your hips.\n2. Press down firmly through your palms to lock out your arms and depress your shoulders.\n3. Lift your hips and extend your legs straight out in front of you at hip height.\n4. Form an "L" shape with your torso and legs, pointing your toes forward.\n5. Squeeze your quadriceps and contract your abs intensely to maintain leg height.\n6. Hold steadily for the desired time before lowering with control.',
        'beginner_tips': 'Start with a tucked L-sit (knees bent to chest) to build shoulder depression and core compression strength first.',
        'recommended_sets': '3–4',
        'recommended_reps': '',
        'recommended_duration': '15–30 seconds',
        'recommended_rest': '60–90 seconds',
    },
    'Lat Pulldown': {
        'description': 'The Lat Pulldown uses a cable machine to develop latissimus dorsi width and upper-back strength, serving as a scalable vertical pulling staple.',
        'instructions': '1. Sit at the lat pulldown machine and adjust the thigh pad so your legs are snug and secure.\n2. Grip the wide bar with an overhand grip slightly wider than your shoulders.\n3. Sit tall with a slight backward lean in your torso and chest lifted.\n4. Pull the bar down toward your upper chest by driving your elbows down and back.\n5. Squeeze your lats tightly as the bar approaches your collarbones.\n6. Slowly let the bar rise back up to a full overhead stretch.',
        'beginner_tips': 'Pull with your elbows and back muscles rather than leaning far back and turning the exercise into a horizontal row.',
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '60–75 seconds',
    },
    'Lateral Raise': {
        'description': 'The Dumbbell Lateral Raise is the premier isolation movement for the lateral deltoids, building shoulder width, roundness, and an athletic V-taper physique.',
        'instructions': '1. Stand tall holding dumbbells at your sides with a slight forward lean and soft knees.\n2. Keep a slight, fixed bend in your elbows throughout the movement.\n3. Raise the dumbbells out to the sides in a wide arc until they reach shoulder level.\n4. Lead the movement with your elbows and keep your pinkies slightly higher than your thumbs.\n5. Pause briefly at the top to feel the lateral shoulder contraction.\n6. Lower the weights slowly and under control back to your sides.',
        'beginner_tips': 'Do not swing your body or use heavy weights; light weights lifted strictly produce far superior side-delt growth.',
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '45–60 seconds',
    },
    'Leg Curl': {
        'description': 'The Machine Leg Curl isolates the hamstrings through knee flexion, developing knee joint resilience, posterior leg symmetry, and hamstring thickness.',
        'instructions': '1. Lie face down on the prone leg curl machine or sit securely in the seated leg curl machine.\n2. Position the padded lever against the back of your lower legs just below the calf muscles.\n3. Grip the machine handles firmly to anchor your hips down into the bench pad.\n4. Curl your heels toward your glutes smoothly by contracting your hamstrings.\n5. Squeeze your hamstrings hard at peak contraction for one second.\n6. Lower the weight slowly back to the starting extended position under control.',
        'beginner_tips': 'Keep your hips pressed flat against the pad throughout the curl rather than letting your pelvis rise during heavy reps.',
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
    'Leg Extension': {
        'description': 'The Leg Extension machine isolates the four heads of the quadriceps through knee extension, building quadricep definition and strengthening the patellar tendon.',
        'instructions': '1. Sit on the leg extension machine with your back flat against the backrest.\n2. Adjust the shin pad so it rests comfortably against your lower shins just above the ankles.\n3. Grip the side handles to stabilize your pelvis and upper body.\n4. Extend your legs upward until your knees are fully straight.\n5. Squeeze your quadriceps intensely at full extension for one to two seconds.\n6. Lower the weight slowly and under control back to the starting 90-degree position.',
        'beginner_tips': 'Control the descent under a slow two-second tempo instead of letting the weight stack crash down between reps.',
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
    'Leg Press': {
        'description': 'The Leg Press machine enables heavy lower-body loading with reduced spinal fatigue, building massive quadricep, glute, and hamstring strength in a supported position.',
        'instructions': '1. Sit in the machine with your back and head firmly supported against the padded backrest.\n2. Place your feet shoulder-width apart on the sled platform with toes angled slightly outward.\n3. Release the safety levers and unrack the weight with straight (unlocked) legs.\n4. Lower the sled smoothly by bending your knees until they reach approximately a 90-degree angle.\n5. Drive forcefully through your heels and midfoot to press the platform back up.\n6. Stop just short of locking your knees at the top before repeating.',
        'beginner_tips': 'Never lock your knees out aggressively at the top, and ensure your lower back stays firmly pinned to the backrest.',
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '75–90 seconds',
    },
    'Leg Raise': {
        'description': 'The Lying Leg Raise targets the lower rectus abdominis and deep hip flexors, building core compression strength and spinal control from the floor.',
        'instructions': '1. Lie flat on your back on a mat with your legs extended straight and hands resting at your sides.\n2. Press your lower back firmly into the floor and engage your abdominal wall.\n3. Keeping your legs straight, lift them together toward the ceiling until they reach roughly 90 degrees.\n4. Squeeze your lower abs at the top of the lift.\n5. Slowly lower your legs back toward the floor under control.\n6. Stop hovering your heels just one to two inches above the ground before starting the next rep.',
        'beginner_tips': 'Do not let your lower back arch off the floor on the way down; bend your knees slightly if needed to keep your spine flat.',
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '45–60 seconds',
    },
    'Lunges': {
        'description': 'Bodyweight Lunges build unilateral leg strength, improve hip mobility, and challenge balance across the quadriceps, glutes, hamstrings, and calves.',
        'instructions': '1. Stand tall with your feet hip-width apart, hands on hips or at your sides, and core braced.\n2. Take a controlled step forward with your right leg.\n3. Lower your hips until both your front and back knees are bent at roughly 90-degree angles.\n4. Keep your front knee tracking over your toes and your torso tall and upright.\n5. Drive through your front heel to push back to the starting standing position.\n6. Repeat the movement stepping forward with your left leg and continue alternating.',
        'beginner_tips': 'Take a long enough step so your front knee stays behind your toes and your back knee hovers just above the mat.',
        'recommended_sets': '3',
        'recommended_reps': '10–12 each leg',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
    'Mountain Climbers': {
        'description': 'Mountain Climbers are a dynamic bodyweight conditioning movement that combines plank core stabilization with high-tempo knee drives to build stamina and core power.',
        'instructions': '1. Start in a strong push-up plank position with hands stacked directly beneath your shoulders.\n2. Keep your body in a straight line from head to heels with abs and glutes engaged.\n3. Drive your right knee forward toward your chest without touching your right foot to the floor.\n4. Quickly extend your right leg back while simultaneously driving your left knee forward.\n5. Continue alternating legs in a rapid, continuous "running" rhythm.\n6. Keep your hips level and shoulders stable over your hands throughout the set.',
        'beginner_tips': 'Keep your hips low and avoid bouncing your rear end up into the air as your speed increases.',
        'recommended_sets': '3',
        'recommended_reps': '',
        'recommended_duration': '30–45 seconds',
        'recommended_rest': '45 seconds',
    },
    'Muscle-Up': {
        'description': 'The Muscle-Up is an elite calisthenics movement combining an explosive pull-up, rapid transition, and straight-bar dip into one continuous athletic feat.',
        'instructions': '1. Hang from a pull-up bar using a false grip or strong overhand grip.\n2. Initiate a slight swing or hollow-body Kip to build upward momentum.\n3. Pull explosively toward your upper chest and drive your elbows back and up.\n4. Rapidly transition your chest over the bar by rolling your wrists and shoulders forward.\n5. Press out of the dip position until your arms are fully extended above the bar.\n6. Lower yourself back down smoothly under control into a dead hang.',
        'beginner_tips': 'Master high explosive pull-ups (pulling to sternum) and deep straight-bar dips before attempting the muscle-up transition.',
        'recommended_sets': '3',
        'recommended_reps': '3–6',
        'recommended_duration': '',
        'recommended_rest': '120 seconds',
    },
    'Overhead Press': {
        'description': 'The Standing Barbell Overhead Press is the gold-standard test of vertical pressing power, building massive shoulders, upper-chest, triceps, and standing core stability.',
        'instructions': '1. Unrack a barbell at collarbone height and hold it with an overhand grip just outside your shoulders.\n2. Stand with feet shoulder-width apart, squeeze your glutes, and brace your core.\n3. Tilt your head back slightly to clear the bar path and press the barbell straight upward.\n4. Once the bar passes your forehead, bring your head back under the bar into a neutral position.\n5. Lock out your arms fully overhead with the bar centered directly over your spine.\n6. Lower the barbell under control back down to collarbone height.',
        'beginner_tips': 'Squeeze your glutes and abs hard throughout the press to prevent leaning backward and hyperextending your lumbar spine.',
        'recommended_sets': '3',
        'recommended_reps': '6–8',
        'recommended_duration': '',
        'recommended_rest': '90–120 seconds',
    },
    'Pike Push-Up': {
        'description': 'The Pike Push-Up angles the body into an inverted V-shape, shifting bodyweight onto the shoulders and triceps to build overhead pressing strength for handstands.',
        'instructions': '1. Start in a standard push-up position and walk your feet forward into a pike (inverted V-shape).\n2. Keep your legs as straight as possible and hips pushed high toward the ceiling.\n3. Look back toward your toes to maintain a neutral cervical spine.\n4. Lower your head forward and down between your hands, forming a tripod with your head and palms.\n5. Descend until the crown of your head lightly grazes the floor.\n6. Press firmly through your hands and shoulders upward and backward to the starting pike position.',
        'beginner_tips': 'Keep your hips high over your shoulders; do not let your hips sag into a regular push-up.',
        'recommended_sets': '3',
        'recommended_reps': '8–12',
        'recommended_duration': '',
        'recommended_rest': '60–75 seconds',
    },
    'Pistol Squat': {
        'description': 'The Pistol Squat is an advanced unilateral bodyweight exercise that builds extraordinary single-leg strength, balance, ankle dorsiflexion, and knee stability.',
        'instructions': '1. Stand tall on your right leg with your left leg extended straight out in front of you.\n2. Reach your arms forward to counterbalance your body weight.\n3. Push your hips back and bend your right knee to descend smoothly into a deep single-leg squat.\n4. Descend until your right hamstring rests against your calf, keeping your left leg off the floor.\n5. Drive through your right heel and midfoot to stand all the way back up.\n6. Complete all reps on one leg before switching to the other.',
        'beginner_tips': 'Hold onto a pole or sit down onto a bench first to build the necessary balance and single-leg strength progressively.',
        'recommended_sets': '3',
        'recommended_reps': '5–8 each leg',
        'recommended_duration': '',
        'recommended_rest': '90 seconds',
    },
    'Plank': {
        'description': 'The Forearm Plank is a foundational isometric core builder that trains the entire abdominal wall, transverse abdominis, glutes, and shoulders to resist spinal extension.',
        'instructions': '1. Lie face down and prop yourself up onto your forearms with elbows stacked under shoulders.\n2. Step your feet back and lift your hips so your body forms a straight line from head to heels.\n3. Tuck your pelvis slightly, squeeze your glutes, and pull your navel toward your spine.\n4. Keep your neck neutral by gazing at the floor between your forearms.\n5. Breathe smoothly while maintaining maximum full-body muscular tension.\n6. Hold for the prescribed duration without letting your hips sag or hike up.',
        'beginner_tips': 'Do not let your lower back sag toward the floor; squeeze your glutes and imagine pulling your elbows toward your toes.',
        'recommended_sets': '3',
        'recommended_reps': '',
        'recommended_duration': '30–45 seconds',
        'recommended_rest': '45 seconds',
    },
    'Preacher Curl': {
        'description': 'The Preacher Curl rests the upper arms on an angled pad to eliminate momentum, isolating the short head of the bicep for peak growth and strict arm development.',
        'instructions': '1. Sit at a preacher bench and rest the backs of your upper arms flat against the angled pad.\n2. Grip the barbell or dumbbells with an underhand grip, palms facing upward.\n3. Extend your arms down along the pad without violently hyperextending your elbows.\n4. Curl the weight upward toward your shoulders by contracting your biceps.\n5. Squeeze your biceps firmly at the top of the range of motion.\n6. Lower the weight slowly and under control back down along the pad.',
        'beginner_tips': 'Avoid dropping the weight quickly at the bottom of the pad to protect your bicep tendons from sudden shock.',
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
    'Pull-Up': {
        'description': 'The Pull-Up is the gold-standard bodyweight pulling exercise, building incredible lat width, upper-back thickness, bicep power, and functional grip strength.',
        'instructions': '1. Grip a pull-up bar with an overhand grip slightly wider than your shoulders.\n2. Hang at full arm extension with your core engaged and shoulder blades set down.\n3. Drive your elbows down toward your ribs to pull your chest up toward the bar.\n4. Pull until your chin is clearly over the top of the bar.\n5. Squeeze your lats and upper back at the peak of the movement.\n6. Lower yourself slowly and under control back to a dead hang.',
        'beginner_tips': 'Do not swing or kick your legs; perform each repetition with a full range of motion from a complete hang to chin over bar.',
        'recommended_sets': '3',
        'recommended_reps': '6–10',
        'recommended_duration': '',
        'recommended_rest': '90 seconds',
    },
    'Push-Up': {
        'description': 'The standard Push-Up is a classic calisthenics movement that strengthens the chest, anterior deltoids, triceps, and core into a unified pressing system.',
        'instructions': '1. Start in a high plank with your hands planted slightly wider than shoulder-width.\n2. Form a straight line from your head to your heels with core and glutes engaged.\n3. Lower your body by bending your elbows at roughly a 45-degree angle to your torso.\n4. Descend until your chest is roughly one inch above the floor.\n5. Push forcefully through your hands to extend your arms back to the starting plank.\n6. Squeeze your chest at the top before starting the next rep.',
        'beginner_tips': 'Keep your elbows tracking back diagonally like an arrow rather than flaring out perpendicular to your torso.',
        'recommended_sets': '3',
        'recommended_reps': '10–15',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
    'Rear Delt Fly': {
        'description': 'The Rear Delt Fly isolates the posterior deltoid head and upper back musculature, improving shoulder balance, posture, and upper-back thickness.',
        'instructions': '1. Stand with feet hip-width apart and hinge at your hips until your torso is nearly parallel to the floor.\n2. Hold dumbbells hanging straight down beneath your chest with palms facing each other.\n3. Keep a slight bend in your elbows and a flat, neutral spine.\n4. Raise the dumbbells out to the sides in a wide arc until your upper arms are level with your torso.\n5. Squeeze your rear deltoids and shoulder blades together at the top.\n6. Lower the weights slowly back down to the starting position.',
        'beginner_tips': 'Lead with your elbows and avoid standing up or jerking your torso as you raise the weights.',
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '45–60 seconds',
    },
    'Romanian Deadlift': {
        'description': 'The Romanian Deadlift (RDL) emphasizes the eccentric hip-hinge to load and develop the hamstrings, glutes, and lower back with minimal knee flexion.',
        'instructions': '1. Stand tall holding dumbbells or a barbell at hip level with feet hip-width apart.\n2. Keep a soft bend in your knees and maintain a flat, neutral spine.\n3. Hinge backward at your hips, sending your glutes toward the wall behind you.\n4. Lower the weight along your shins until you feel a deep stretch in your hamstrings.\n5. Stop when your hips stop moving backward (usually around mid-shin level).\n6. Drive your hips forward and squeeze your glutes to return to a tall standing posture.',
        'beginner_tips': 'Think of pushing your hips backward rather than bending forward; keep the weights skimming close to your legs.',
        'recommended_sets': '3',
        'recommended_reps': '8–10',
        'recommended_duration': '',
        'recommended_rest': '90 seconds',
    },
    'Running': {
        'description': 'Running is a dynamic cardiovascular exercise that builds heart and lung capacity, enhances bone density, and burns calories at a high metabolic rate.',
        'instructions': '1. Stand tall with a slight forward lean from the ankles, keeping your chest open.\n2. Push off with the ball of your rear foot and drive your opposite knee forward.\n3. Land softly under your center of gravity with a midfoot strike.\n4. Pump your arms rhythmically forward and backward with elbows bent at 90 degrees.\n5. Maintain a steady breathing pattern synchronized with your stride.\n6. Gradually slow your pace to a jog and walk to cool down at the end of the run.',
        'beginner_tips': 'Avoid overstriding (landing far in front of your body on your heels); take quick, short strides beneath your hips.',
        'recommended_sets': '1',
        'recommended_reps': '',
        'recommended_duration': '20–30 minutes',
        'recommended_rest': 'As needed',
    },
    'Russian Twist': {
        'description': 'The Russian Twist is a rotational core exercise that challenges the obliques and transverse abdominis to resist fatigue and stabilize the torso during twisting.',
        'instructions': '1. Sit on a mat with your knees bent and feet flat on the floor.\n2. Lean your torso back at a 45-degree angle to engage your abdominal wall.\n3. Lift your feet slightly off the floor for more difficulty or keep heels lightly grounded.\n4. Clasp your hands in front of your chest and rotate your torso to the right, tapping the mat.\n5. Rotate smoothly back across to the left side and tap the mat.\n6. Continue alternating sides under steady control without rounding your lower back.',
        'beginner_tips': 'Rotate your entire ribcage and shoulders from side to side rather than just waving your hands back and forth.',
        'recommended_sets': '3',
        'recommended_reps': '16–20 total',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
    },
    'Seated Cable Row': {
        'description': 'The Seated Cable Row is a classic horizontal pull that builds mid-back thickness across the rhomboids, middle trapezius, lats, and biceps.',
        'instructions': '1. Sit on the row machine bench and place your feet on the footplates with knees slightly bent.\n2. Grasp the V-bar handle and sit up tall with a flat back and shoulders relaxed.\n3. Pull the handle toward your lower abdomen by driving your elbows backward.\n4. Retract and squeeze your shoulder blades firmly together at peak contraction.\n5. Slowly extend your arms forward to return to the starting stretch without rounding your back.\n6. Maintain an upright torso throughout the pull.',
        'beginner_tips': 'Avoid leaning excessively forward and backward; keep your torso mostly upright and row with your back muscles.',
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '60–75 seconds',
    },
    'Side Plank': {
        'description': 'The Side Plank isolates the lateral core, specifically the obliques and quadratus lumborum, building lateral hip stability and spinal resilience.',
        'instructions': '1. Lie on your right side with your legs straight and feet stacked or staggered.\n2. Place your right elbow directly beneath your right shoulder, forearm flat on the floor.\n3. Engage your core and lift your hips off the ground until your body forms a straight diagonal line.\n4. Keep your neck neutral and reach your left arm upward or place your left hand on your hip.\n5. Hold the position steadily while breathing rhythmically.\n6. Lower your hips down smoothly before switching to the left side.',
        'beginner_tips': 'Do not allow your bottom hip to sag toward the floor; actively press the floor away with your supporting forearm and feet.',
        'recommended_sets': '3',
        'recommended_reps': '',
        'recommended_duration': '20–30 seconds each side',
        'recommended_rest': '45 seconds',
    },
    'Sit-Up': {
        'description': 'The Sit-Up is a traditional abdominal conditioning exercise that flexes the spine and hips, building muscular endurance in the rectus abdominis and hip flexors.',
        'instructions': '1. Lie flat on your back on a mat with your knees bent and feet flat on the floor.\n2. Cross your arms over your chest or place fingertips lightly behind your ears.\n3. Contract your abdominals to curl your spine and lift your torso all the way up to your thighs.\n4. Exhale as you reach the top upright sitting position.\n5. Slowly roll your spine back down one vertebra at a time.\n6. Touch your shoulder blades lightly to the mat and immediately start the next repetition.',
        'beginner_tips': 'Lower your back down slowly with control rather than flopping onto the floor to keep constant tension on your abs.',
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
    },
    'Skull Crushers': {
        'description': 'Lying Tricep Extensions (Skull Crushers) isolate the long and medial heads of the triceps brachii, building arm thickness and lockout power.',
        'instructions': '1. Lie flat on a bench holding an EZ-bar or dumbbells directly over your chest with arms extended.\n2. Keep your upper arms stationary and angled slightly backward toward your head.\n3. Bend your elbows to lower the weight under control toward your forehead or crown of your head.\n4. Stop when your elbows reach a 90-degree bend and you feel a deep tricep stretch.\n5. Extend your elbows to press the weight back up to the starting position.\n6. Squeeze your triceps hard at the top before starting the next rep.',
        'beginner_tips': 'Keep your elbows tucked in shoulder-width apart; do not let them flare out wide to the sides.',
        'recommended_sets': '3',
        'recommended_reps': '10–12',
        'recommended_duration': '',
        'recommended_rest': '60–75 seconds',
    },
    'Squat': {
        'description': 'The Barbell Squat is the foundational compound lower-body exercise, building formidable strength and size in the quadriceps, glutes, hamstrings, and core.',
        'instructions': '1. Step under the barbell, resting it comfortably across your upper traps, and grip it firmly.\n2. Unrack the bar and take two steps back, setting feet shoulder-width apart with toes flared.\n3. Take a deep diaphragmatic breath, brace your core, and push your hips back while bending your knees.\n4. Descend smoothly until your hip crease drops below the top of your knees.\n5. Drive hard through the middle of your feet to stand back up.\n6. Exhale at the top and reset your core brace before the next repetition.',
        'beginner_tips': 'Keep your heels glued to the floor and ensure your knees push outward in line with your toes throughout the descent.',
        'recommended_sets': '3',
        'recommended_reps': '8–10',
        'recommended_duration': '',
        'recommended_rest': '90 seconds',
    },
    'Step-Up': {
        'description': 'The Step-Up is a functional unilateral leg builder that strengthens the quadriceps and glutes while improving single-leg balance and joint coordination.',
        'instructions': '1. Stand in front of a sturdy bench, plyo box, or step with feet hip-width apart.\n2. Place your entire right foot firmly onto the center of the step.\n3. Drive down through your right heel to lift your body up onto the platform.\n4. Bring your left foot to meet your right at the top, standing fully upright.\n5. Step back down under control with your left foot first, followed by your right.\n6. Alternate lead legs or complete all reps on one side before switching.',
        'beginner_tips': 'Do not jump off your trailing back foot; make the front leg on the box do the entirety of the lifting work.',
        'recommended_sets': '3',
        'recommended_reps': '10–12 each leg',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
    },
    'Thruster': {
        'description': 'The Thruster combines a front squat with an overhead press in one fluid kinetic movement, creating a formidable full-body conditioning and power exercise.',
        'instructions': '1. Hold weights at shoulder level in a front rack position with feet shoulder-width apart.\n2. Brace your core and lower into a deep squat until thighs are parallel to the floor.\n3. Drive explosively out of the squat by pushing through your midfoot.\n4. Use the upward momentum of your legs to press the weights seamlessly overhead.\n5. Lock out your arms fully overhead as your hips reach full extension.\n6. Lower the weights smoothly back to your shoulders as you immediately descend into the next squat.',
        'beginner_tips': 'Use the explosive power of your legs to launch the weights overhead rather than performing a separate squat and press.',
        'recommended_sets': '3',
        'recommended_reps': '8–10',
        'recommended_duration': '',
        'recommended_rest': '90 seconds',
    },
    'Tricep Pushdown': {
        'description': 'The Cable Tricep Pushdown isolates the triceps brachii through elbow extension, creating continuous tension to build arm strength and muscle tone.',
        'instructions': '1. Attach a rope or straight bar to a high cable pulley and grip it at chest height.\n2. Stand tall with a slight forward lean and tuck your elbows firmly against your sides.\n3. Push the attachment downward by contracting your triceps until your arms are fully straight.\n4. Squeeze your triceps intensely at the bottom of the movement for one second.\n5. Slowly allow the attachment to rise back up to chest height while keeping elbows pinned.\n6. Repeat smoothly without using body momentum.',
        'beginner_tips': 'Keep your upper arms locked stationary against your ribs so only your forearms and elbows move.',
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '45–60 seconds',
    },
    'Turkish Get-Up': {
        'description': 'The Turkish Get-Up is a master-level full-body mobility and stability exercise that transitions from lying to standing with a weight locked overhead.',
        'instructions': '1. Lie on your back holding a kettlebell pressed straight up in your right hand with right knee bent.\n2. Roll onto your left elbow and then press up onto your left palm while keeping the weight locked overhead.\n3. Bridge your hips up and sweep your left leg back into a half-kneeling position.\n4. Bring your torso upright in the lunge while keeping your gaze on the overhead kettlebell.\n5. Stand up fully from the lunge with the weight stabilized directly above your shoulder.\n6. Reverse all steps in exact order to return safely to the floor.',
        'beginner_tips': 'Never take your eyes off the weight overhead, and master the movement with an empty hand or shoe before adding weight.',
        'recommended_sets': '3',
        'recommended_reps': '3–5 each side',
        'recommended_duration': '',
        'recommended_rest': '90 seconds',
    },
    'Walking': {
        'description': 'Walking is a foundational, sustainable low-impact aerobic exercise that enhances cardiovascular health, assists in recovery, and supports fat loss.',
        'instructions': '1. Stand tall with your head up, shoulders relaxed, and gaze looking forward.\n2. Step forward with your lead foot, striking lightly with your heel and rolling through your toes.\n3. Push off from the ball of your trailing foot to initiate the next step.\n4. Swing your arms naturally from your shoulders in opposition to your leg stride.\n5. Maintain a brisk, steady pace and breathe rhythmically.\n6. Continue walking for your prescribed duration or step count.',
        'beginner_tips': 'Walk at a brisk pace that raises your heart rate slightly while still allowing you to carry on a conversation.',
        'recommended_sets': '1',
        'recommended_reps': '',
        'recommended_duration': '30–45 minutes',
        'recommended_rest': 'As needed',
    },
    'Walking Lunges': {
        'description': 'Walking Lunges build dynamic single-leg strength, hip stability, and cardiovascular endurance by traveling forward with deep, alternating lunges.',
        'instructions': '1. Stand tall at the end of a clear walkway with feet hip-width apart and core braced.\n2. Step forward with your right foot and descend until both knees are bent at roughly 90 degrees.\n3. Ensure your right knee stays aligned with your toes and your left knee hovers just above the mat.\n4. Drive through your right heel to rise and step your left leg directly forward into the next lunge.\n5. Continue stepping forward in a fluid, continuous alternating walking pattern.\n6. Maintain an upright torso and steady balance throughout the walkway.',
        'beginner_tips': 'Control your descent on every step so your trailing knee never bangs into the floor.',
        'recommended_sets': '3',
        'recommended_reps': '10–12 each leg',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
    'Wall Push-Up': {
        'description': 'The Wall Push-Up is the gentlest entry-level pressing variation, allowing beginners to build chest, shoulder, and tricep strength with minimal joint strain.',
        'instructions': '1. Stand facing a wall about arm’s length away with feet hip-width apart.\n2. Place your palms flat against the wall at shoulder height and shoulder-width apart.\n3. Keep your body in a straight plank line from your head to your heels.\n4. Bend your elbows to lower your chest and face toward the wall.\n5. Stop when your nose is just an inch from the wall.\n6. Push firmly through your hands to return to full arm extension.',
        'beginner_tips': 'Step further back from the wall to increase resistance as your pressing strength develops.',
        'recommended_sets': '3',
        'recommended_reps': '12–15',
        'recommended_duration': '',
        'recommended_rest': '45 seconds',
    },
    'Wide Push-Up': {
        'description': 'The Wide Push-Up places the hands wider than shoulder-width to place greater horizontal stretch and mechanical load across the outer chest muscles.',
        'instructions': '1. Assume a push-up position with hands placed significantly wider than shoulder-width.\n2. Align your body in a straight line from your head to your heels with core braced.\n3. Lower your chest toward the floor by bending your elbows out at roughly 60 degrees.\n4. Descend until your chest is approximately one inch above the ground.\n5. Press firmly through the floor to return to full arm extension.\n6. Squeeze your pectoral muscles at the top before starting the next rep.',
        'beginner_tips': 'Do not place your hands excessively wide if you feel discomfort in your shoulders; find a comfortable, wide width.',
        'recommended_sets': '3',
        'recommended_reps': '10–15',
        'recommended_duration': '',
        'recommended_rest': '60 seconds',
    },
}
